// Copyright (C) Fasten Health, Inc. - All Rights Reserved.
//
// THIS FILE IS GENERATED BY https://github.com/fastenhealth/fasten-sources-gen
// PLEASE DO NOT EDIT BY HAND

package source

import (
	platform "github.com/fastenhealth/fasten-sources/definitions/internal/platform"
	models "github.com/fastenhealth/fasten-sources/definitions/models"
	pkg "github.com/fastenhealth/fasten-sources/pkg"
)

// https://fhir.fhirpoint.open.allscripts.com/fhirroute/fhir/10035290/metadata
func GetSourceAdvancedUrology(env pkg.FastenLighthouseEnvType, clientIdLookup map[pkg.SourceType]string) (models.LighthouseSourceDefinition, error) {
	sourceDef, err := platform.GetSourceAllscripts(env, clientIdLookup)
	sourceDef.AuthorizationEndpoint = "https://fhir.fhirpoint.open.allscripts.com/fhirroute/authorization/10035290/connect/authorize"
	sourceDef.TokenEndpoint = "https://fhir.fhirpoint.open.allscripts.com/fhirroute/authorization/10035290/connect/token"

	sourceDef.Audience = "https://fhir.fhirpoint.open.allscripts.com/fhirroute/fhir/10035290"

	sourceDef.ApiEndpointBaseUrl = "https://fhir.fhirpoint.open.allscripts.com/fhirroute/fhir/10035290"
	// retrieve client-id, if available
	if clientId, clientIdOk := clientIdLookup[pkg.SourceTypeAdvancedUrology]; clientIdOk {
		sourceDef.ClientId = clientId
	}
	sourceDef.RedirectUri = pkg.GetCallbackEndpoint(string(pkg.SourceTypeAllscripts))

	sourceDef.Display = "Advanced Urology"
	sourceDef.SourceType = pkg.SourceTypeAdvancedUrology
	sourceDef.Category = []string{"207RC0000X", "207RI0011X", "208600000X", "208800000X", "207R00000X", "332900000X"}
	sourceDef.Aliases = []string{"ADVANCED UROLOGY", "RALEIGH CARDIAC", "RALEIGH CARDIAC CENTER", "RALEIGH GENERAL SURGERY", "RALEIGH HEART AND HEALTH CLINIC", "SOUTHEAST UROLOGY"}
	sourceDef.Identifiers = map[string][]string{"http://hl7.org/fhir/sid/us-npi": []string{"1114475746", "1598262016", "1801126479", "1023589884"}}
	sourceDef.Hidden = true
	sourceDef.PatientAccessUrl = "https://crhealthcare.org/locations/advanced-urology/"
	sourceDef.SecretKeyPrefix = "allscripts"

	return sourceDef, err
}
