// Copyright (C) Fasten Health, Inc. - All Rights Reserved.
//
// THIS FILE IS GENERATED BY https://github.com/fastenhealth/fasten-sources-gen
// PLEASE DO NOT EDIT BY HAND

package source

import (
	platform "github.com/fastenhealth/fasten-sources/definitions/internal/platform"
	models "github.com/fastenhealth/fasten-sources/definitions/models"
	pkg "github.com/fastenhealth/fasten-sources/pkg"
)

// https://epicproxy.ardenthealth.com/fhir/api/FHIR/R4/metadata
func GetSourceArdent(env pkg.FastenLighthouseEnvType, clientIdLookup map[pkg.SourceType]string) (models.LighthouseSourceDefinition, error) {
	sourceDef, err := platform.GetSourceEpicLegacy(env, clientIdLookup)
	sourceDef.AuthorizationEndpoint = "https://epicproxy.ardenthealth.com/fhir/oauth2/authorize"
	sourceDef.TokenEndpoint = "https://epicproxy.ardenthealth.com/fhir/oauth2/token"

	sourceDef.Audience = "https://epicproxy.ardenthealth.com/fhir/api/FHIR/R4"

	sourceDef.ApiEndpointBaseUrl = "https://epicproxy.ardenthealth.com/fhir/api/FHIR/R4"
	// retrieve client-id, if available
	if clientId, clientIdOk := clientIdLookup[pkg.SourceTypeArdent]; clientIdOk {
		sourceDef.ClientId = clientId
	}
	sourceDef.RedirectUri = pkg.GetCallbackEndpoint(string(pkg.SourceTypeEpicLegacy))

	sourceDef.Display = "Ardent"
	sourceDef.SourceType = pkg.SourceTypeArdent
	sourceDef.Category = []string{}
	sourceDef.Aliases = []string{}
	sourceDef.SecretKeyPrefix = "epic-legacy"

	return sourceDef, err
}
