// Copyright (C) Fasten Health, Inc. - All Rights Reserved.
//
// THIS FILE IS GENERATED BY https://github.com/fastenhealth/fasten-sources-gen
// PLEASE DO NOT EDIT BY HAND

package source

import (
	platform "github.com/fastenhealth/fasten-sources/definitions/internal/platform"
	models "github.com/fastenhealth/fasten-sources/definitions/models"
	pkg "github.com/fastenhealth/fasten-sources/pkg"
)

// https://eprescribe.wfhc.org/FHIRproxy/api/FHIR/R4/metadata
func GetSourceAscensionWisconsin(env pkg.FastenLighthouseEnvType, clientIdLookup map[pkg.SourceType]string) (models.LighthouseSourceDefinition, error) {
	sourceDef, err := platform.GetSourceEpic(env, clientIdLookup)
	sourceDef.AuthorizationEndpoint = "https://eprescribe.wfhc.org/FHIRproxy/oauth2/authorize"
	sourceDef.TokenEndpoint = "https://eprescribe.wfhc.org/FHIRproxy/oauth2/token"

	sourceDef.Audience = "https://eprescribe.wfhc.org/FHIRproxy/api/FHIR/R4"

	sourceDef.ApiEndpointBaseUrl = "https://eprescribe.wfhc.org/FHIRproxy/api/FHIR/R4"
	// retrieve client-id, if available
	if clientId, clientIdOk := clientIdLookup[pkg.SourceTypeAscensionWisconsin]; clientIdOk {
		sourceDef.ClientId = clientId
	}
	sourceDef.RedirectUri = pkg.GetCallbackEndpoint(string(pkg.SourceTypeEpic))

	sourceDef.Display = "Ascension Wisconsin"
	sourceDef.SourceType = pkg.SourceTypeAscensionWisconsin
	sourceDef.SecretKeyPrefix = "epic"

	return sourceDef, err
}
