// Copyright (C) Fasten Health, Inc. - All Rights Reserved.
//
// THIS FILE IS GENERATED BY https://github.com/fastenhealth/fasten-sources-gen
// PLEASE DO NOT EDIT BY HAND

package source

import (
	platform "github.com/fastenhealth/fasten-sources/definitions/internal/platform"
	models "github.com/fastenhealth/fasten-sources/definitions/models"
	pkg "github.com/fastenhealth/fasten-sources/pkg"
)

// https://api.platform.athenahealth.com/fhir/r4/metadata
func GetSourceBaptistHealthMedicalGroupInc1(env pkg.FastenLighthouseEnvType, clientIdLookup map[pkg.SourceType]string) (models.LighthouseSourceDefinition, error) {
	sourceDef, err := platform.GetSourceAthena(env, clientIdLookup)
	sourceDef.AuthorizationEndpoint = "https://api.platform.athenahealth.com/oauth2/v1/authorize"
	sourceDef.TokenEndpoint = "https://api.platform.athenahealth.com/oauth2/v1/token"

	sourceDef.Audience = "https://api.platform.athenahealth.com/fhir/r4"

	sourceDef.ApiEndpointBaseUrl = "https://api.platform.athenahealth.com/fhir/r4"
	// retrieve client-id, if available
	if clientId, clientIdOk := clientIdLookup[pkg.SourceTypeBaptistHealthMedicalGroupInc1]; clientIdOk {
		sourceDef.ClientId = clientId
	}
	sourceDef.RedirectUri = pkg.GetCallbackEndpoint(string(pkg.SourceTypeAthena))

	sourceDef.Display = "Baptist Health Medical Group Inc"
	sourceDef.SourceType = pkg.SourceTypeBaptistHealthMedicalGroupInc1
	sourceDef.Category = []string{"101YP2500X", "103T00000X", "1041C0700X", "207P00000X", "207PP0204X", "207Q00000X", "207R00000X", "207V00000X", "208000000X", "2084N0400X", "2084P0800X", "2085P0229X", "2085R0001X", "208600000X", "208C00000X", "208D00000X", "208G00000X", "213E00000X", "225100000X", "261Q00000X", "261QP2300X", "261QR1300X", "363A00000X", "363AS0400X", "363L00000X"}
	sourceDef.Aliases = []string{"BEREA RURAL HEALTH CENTER", "BHMG PSYCHIATRY CORBIN", "BHMG WOMAN'S CARE", "BRANNON CROSSING FAMILY MEDICINE", "BRANNON CROSSING URGENT CARE", "PRINCETON RURAL HEALTH CLINIC", "RURAL HEALTH CLINIC BARBOURVILLE", "RURAL HEALTH CLINIC WILLIAMSBURG", "SCOTTSBURG PRIMARY CARE"}
	sourceDef.Identifiers = map[string][]string{"http://hl7.org/fhir/sid/us-npi": []string{"1104471440", "1184119398", "1255805586", "1265072946", "1447728043", "1467057042", "1518360296", "1548755739", "1619567559", "1689762973", "1831668375"}}
	sourceDef.BrandLogo = "baptist-health-medical-group-inc.svg"
	sourceDef.PatientAccessUrl = "https://www.baptisthealth.com/about/baptist-health-medical-group"
	sourceDef.SecretKeyPrefix = "athena"

	return sourceDef, err
}
