// Copyright (C) Fasten Health, Inc. - All Rights Reserved.
//
// THIS FILE IS GENERATED BY https://github.com/fastenhealth/fasten-sources-gen
// PLEASE DO NOT EDIT BY HAND

package source

import (
	platform "github.com/fastenhealth/fasten-sources/definitions/internal/platform"
	models "github.com/fastenhealth/fasten-sources/definitions/models"
	pkg "github.com/fastenhealth/fasten-sources/pkg"
)

// https://fhir-myrecord.cerner.com/r4/r2GtnbpYK4vtuAbMjau8TiI_I1r8CPyN/metadata
func GetSourceCenterForManualMedicine(env pkg.FastenLighthouseEnvType, clientIdLookup map[pkg.SourceType]string) (models.LighthouseSourceDefinition, error) {
	sourceDef, err := platform.GetSourceCerner(env, clientIdLookup)
	sourceDef.AuthorizationEndpoint = "https://authorization.cerner.com/tenants/r2GtnbpYK4vtuAbMjau8TiI_I1r8CPyN/protocols/oauth2/profiles/smart-v1/personas/patient/authorize"
	sourceDef.TokenEndpoint = "https://authorization.cerner.com/tenants/r2GtnbpYK4vtuAbMjau8TiI_I1r8CPyN/protocols/oauth2/profiles/smart-v1/token"
	sourceDef.IntrospectionEndpoint = "https://authorization.cerner.com/tokeninfo"

	sourceDef.Audience = "https://fhir-myrecord.cerner.com/r4/r2GtnbpYK4vtuAbMjau8TiI_I1r8CPyN"

	sourceDef.ApiEndpointBaseUrl = "https://fhir-myrecord.cerner.com/r4/r2GtnbpYK4vtuAbMjau8TiI_I1r8CPyN"
	// retrieve client-id, if available
	if clientId, clientIdOk := clientIdLookup[pkg.SourceTypeCenterForManualMedicine]; clientIdOk {
		sourceDef.ClientId = clientId
	}
	sourceDef.RedirectUri = pkg.GetCallbackEndpoint(string(pkg.SourceTypeCerner))

	sourceDef.Display = "Center for Manual Medicine"
	sourceDef.SourceType = pkg.SourceTypeCenterForManualMedicine
	sourceDef.Category = []string{}
	sourceDef.Aliases = []string{}
	sourceDef.PatientAccessUrl = "https://www.ctrmm.com/"
	sourceDef.SecretKeyPrefix = "cerner"

	return sourceDef, err
}
