// Copyright (C) Fasten Health, Inc. - All Rights Reserved.
//
// THIS FILE IS GENERATED BY https://github.com/fastenhealth/fasten-sources-gen
// PLEASE DO NOT EDIT BY HAND

package source

import (
	platform "github.com/fastenhealth/fasten-sources/definitions/internal/platform"
	models "github.com/fastenhealth/fasten-sources/definitions/models"
	pkg "github.com/fastenhealth/fasten-sources/pkg"
)

// https://fhir4.eclinicalworks.com/fhir/r4/ECJBDA/metadata
func GetSourceCentralVirginiaHealthServicesInc(env pkg.FastenLighthouseEnvType, clientIdLookup map[pkg.SourceType]string) (models.LighthouseSourceDefinition, error) {
	sourceDef, err := platform.GetSourceEclinicalworks(env, clientIdLookup)
	sourceDef.AuthorizationEndpoint = "https://oauthserver.eclinicalworks.com/oauth/oauth2/authorize"
	sourceDef.TokenEndpoint = "https://oauthserver.eclinicalworks.com/oauth/oauth2/token"

	sourceDef.Audience = "https://fhir4.eclinicalworks.com/fhir/r4/ECJBDA"

	sourceDef.ApiEndpointBaseUrl = "https://fhir4.eclinicalworks.com/fhir/r4/ECJBDA"
	// retrieve client-id, if available
	if clientId, clientIdOk := clientIdLookup[pkg.SourceTypeCentralVirginiaHealthServicesInc]; clientIdOk {
		sourceDef.ClientId = clientId
	}
	sourceDef.RedirectUri = pkg.GetCallbackEndpoint(string(pkg.SourceTypeEclinicalworks))

	sourceDef.Display = "Central Virginia Health Services Inc"
	sourceDef.SourceType = pkg.SourceTypeCentralVirginiaHealthServicesInc
	sourceDef.Category = []string{"261QF0400X"}
	sourceDef.Aliases = []string{"COMMUNITY HEALTH CENTER OF THE RAPPAHANNOCK REGION", "CVHS BUCKINGHAM", "CVHS CHARLOTTE", "CVHS CHARLOTTESVILLE", "CVHS CHILDREN'S DENTAL", "CVHS CRIMSON CLINIC", "CVHS DOWNTOWN PETERSBURG", "CVHS FARMVILLE", "CVHS FREDERICKSBURG", "CVHS HOPEWELL PRINCE GEORGE", "CVHS KING WILLIAM"}
	sourceDef.Identifiers = map[string][]string{"http://hl7.org/fhir/sid/us-npi": []string{"1134258601", "1215066782", "1235259607", "1548632508", "1730377706", "1801411202", "1891823498", "1902934680", "1972631661", "1992132682"}}
	sourceDef.SecretKeyPrefix = "eclinicalworks"

	return sourceDef, err
}
