// Copyright (C) Fasten Health, Inc. - All Rights Reserved.
//
// THIS FILE IS GENERATED BY https://github.com/fastenhealth/fasten-sources-gen
// PLEASE DO NOT EDIT BY HAND

package source

import (
	platform "github.com/fastenhealth/fasten-sources/definitions/internal/platform"
	models "github.com/fastenhealth/fasten-sources/definitions/models"
	pkg "github.com/fastenhealth/fasten-sources/pkg"
)

// https://fhir-myrecord.cerner.com/r4/2d405cde-1d8b-4a50-adff-ca7776cd856e/metadata
func GetSourceCherokeeNation(env pkg.FastenLighthouseEnvType, clientIdLookup map[pkg.SourceType]string) (models.LighthouseSourceDefinition, error) {
	sourceDef, err := platform.GetSourceCerner(env, clientIdLookup)
	sourceDef.AuthorizationEndpoint = "https://authorization.cerner.com/tenants/2d405cde-1d8b-4a50-adff-ca7776cd856e/protocols/oauth2/profiles/smart-v1/personas/patient/authorize"
	sourceDef.TokenEndpoint = "https://authorization.cerner.com/tenants/2d405cde-1d8b-4a50-adff-ca7776cd856e/protocols/oauth2/profiles/smart-v1/token"
	sourceDef.IntrospectionEndpoint = "https://authorization.cerner.com/tokeninfo"

	sourceDef.Audience = "https://fhir-myrecord.cerner.com/r4/2d405cde-1d8b-4a50-adff-ca7776cd856e"

	sourceDef.ApiEndpointBaseUrl = "https://fhir-myrecord.cerner.com/r4/2d405cde-1d8b-4a50-adff-ca7776cd856e"
	// retrieve client-id, if available
	if clientId, clientIdOk := clientIdLookup[pkg.SourceTypeCherokeeNation]; clientIdOk {
		sourceDef.ClientId = clientId
	}
	sourceDef.RedirectUri = pkg.GetCallbackEndpoint(string(pkg.SourceTypeCerner))

	sourceDef.Display = "Cherokee Nation"
	sourceDef.SourceType = pkg.SourceTypeCherokeeNation
	sourceDef.Category = []string{"261QM1300X", "261QM0850X", "3336C0003X", "3336S0011X", "332800000X", "3416L0300X"}
	sourceDef.Aliases = []string{"COOWEESCOOWEE HEALTH CENTER", "GA DU GI HEALTH CENTER", "HASTINGS EMS", "REDBIRD SMITH HEALTH CENTER", "SAM HIDER HEALTH CENTER", "THREE RIVERS HEALTH CENTER", "VINITA HEALTH CENTER", "W.W. HASTINGS INDIAN HOSPITAL URGENT CARE PHARMACY", "WILMA P. MANKILLER HEALTH CENTER"}
	sourceDef.Identifiers = map[string][]string{"http://hl7.org/fhir/sid/us-npi": []string{"1780692723", "1093722324", "1356787444", "1659388965", "1992711345", "1871972430", "1841207156", "1558377226", "1346623584", "1942947288"}}
	sourceDef.BrandLogo = "cherokee-nation.svg"
	sourceDef.PatientAccessUrl = "https://www.cherokee.org/"
	sourceDef.SecretKeyPrefix = "cerner"

	return sourceDef, err
}
