// Copyright (C) Fasten Health, Inc. - All Rights Reserved.
//
// THIS FILE IS GENERATED BY https://github.com/fastenhealth/fasten-sources-gen
// PLEASE DO NOT EDIT BY HAND

package source

import (
	platform "github.com/fastenhealth/fasten-sources/definitions/internal/platform"
	models "github.com/fastenhealth/fasten-sources/definitions/models"
	pkg "github.com/fastenhealth/fasten-sources/pkg"
)

// https://epicarr.healthcare.cigna.com/FHIR-PRD/api/FHIR/R4/metadata
func GetSourceCignaMedicalGroup(env pkg.FastenLighthouseEnvType, clientIdLookup map[pkg.SourceType]string) (models.LighthouseSourceDefinition, error) {
	sourceDef, err := platform.GetSourceEpic(env, clientIdLookup)
	sourceDef.AuthorizationEndpoint = "https://epicarr.healthcare.cigna.com/FHIR-PRD/oauth2/authorize"
	sourceDef.TokenEndpoint = "https://epicarr.healthcare.cigna.com/FHIR-PRD/oauth2/token"
	sourceDef.RegistrationEndpoint = "https://epicarr.healthcare.cigna.com/FHIR-PRD/oauth2/register"

	sourceDef.Audience = "https://epicarr.healthcare.cigna.com/FHIR-PRD/api/FHIR/R4"

	sourceDef.ApiEndpointBaseUrl = "https://epicarr.healthcare.cigna.com/FHIR-PRD/api/FHIR/R4"
	// retrieve client-id, if available
	if clientId, clientIdOk := clientIdLookup[pkg.SourceTypeCignaMedicalGroup]; clientIdOk {
		sourceDef.ClientId = clientId
	}
	sourceDef.RedirectUri = pkg.GetCallbackEndpoint(string(pkg.SourceTypeEpic))

	sourceDef.Display = "Cigna Medical Group"
	sourceDef.SourceType = pkg.SourceTypeCignaMedicalGroup
	sourceDef.Category = []string{"363L00000X", "261QM1300X"}
	sourceDef.Identifiers = map[string][]string{"http://hl7.org/fhir/sid/us-npi": []string{"1003270596", "1023113271"}}
	sourceDef.SecretKeyPrefix = "epic"

	return sourceDef, err
}
