// Copyright (C) Fasten Health, Inc. - All Rights Reserved.
//
// THIS FILE IS GENERATED BY https://github.com/fastenhealth/fasten-sources-gen
// PLEASE DO NOT EDIT BY HAND

package source

import (
	platform "github.com/fastenhealth/fasten-sources/definitions/internal/platform"
	models "github.com/fastenhealth/fasten-sources/definitions/models"
	pkg "github.com/fastenhealth/fasten-sources/pkg"
)

// https://api.ccf.org/mu/api/FHIR/R4/metadata
func GetSourceClevelandClinic(env pkg.FastenLighthouseEnvType, clientIdLookup map[pkg.SourceType]string) (models.LighthouseSourceDefinition, error) {
	sourceDef, err := platform.GetSourceEpic(env, clientIdLookup)
	sourceDef.AuthorizationEndpoint = "https://api.ccf.org/mu/oauth2/authorize"
	sourceDef.TokenEndpoint = "https://api.ccf.org/mu/oauth2/token"
	sourceDef.RegistrationEndpoint = "https://api.ccf.org/mu/oauth2/register"

	sourceDef.Audience = "https://api.ccf.org/mu/api/FHIR/R4"

	sourceDef.ApiEndpointBaseUrl = "https://api.ccf.org/mu/api/FHIR/R4"
	// retrieve client-id, if available
	if clientId, clientIdOk := clientIdLookup[pkg.SourceTypeClevelandClinic]; clientIdOk {
		sourceDef.ClientId = clientId
	}
	sourceDef.RedirectUri = pkg.GetCallbackEndpoint(string(pkg.SourceTypeEpic))

	sourceDef.Display = "Cleveland Clinic"
	sourceDef.SourceType = pkg.SourceTypeClevelandClinic
	sourceDef.Category = []string{"1835P2201X", "261Q00000X", "261QP2000X", "281P00000X", "282N00000X"}
	sourceDef.Identifiers = map[string][]string{"http://hl7.org/fhir/sid/us-npi": []string{"1053563767", "1104099217", "1275791162", "1336316389", "1356508964", "1487102679", "1558319491", "1629255575", "1841616752", "1962837658"}}
	sourceDef.SecretKeyPrefix = "epic"

	return sourceDef, err
}
