// Copyright (C) Fasten Health, Inc. - All Rights Reserved.
//
// THIS FILE IS GENERATED BY https://github.com/fastenhealth/fasten-sources-gen
// PLEASE DO NOT EDIT BY HAND

package source

import (
	platform "github.com/fastenhealth/fasten-sources/definitions/internal/platform"
	models "github.com/fastenhealth/fasten-sources/definitions/models"
	pkg "github.com/fastenhealth/fasten-sources/pkg"
)

// https://fhir.nextgen.com/nge/prod/fhir-api-r4/fhir/r4/metadata
func GetSourceCollomAndCarneyClinic(env pkg.FastenLighthouseEnvType, clientIdLookup map[pkg.SourceType]string) (models.LighthouseSourceDefinition, error) {
	sourceDef, err := platform.GetSourceNextgen(env, clientIdLookup)
	sourceDef.AuthorizationEndpoint = "https://fhir.nextgen.com/nge/prod/patient-oauth/authorize"
	sourceDef.TokenEndpoint = "https://fhir.nextgen.com/nge/prod/patient-oauth/token"

	sourceDef.Audience = "https://fhir.nextgen.com/nge/prod/fhir-api-r4/fhir/r4"

	sourceDef.ApiEndpointBaseUrl = "https://fhir.nextgen.com/nge/prod/fhir-api-r4/fhir/r4"
	// retrieve client-id, if available
	if clientId, clientIdOk := clientIdLookup[pkg.SourceTypeCollomAndCarneyClinic]; clientIdOk {
		sourceDef.ClientId = clientId
	}
	sourceDef.RedirectUri = pkg.GetCallbackEndpoint(string(pkg.SourceTypeNextgen))

	sourceDef.Display = "Collom and Carney Clinic"
	sourceDef.SourceType = pkg.SourceTypeCollomAndCarneyClinic
	sourceDef.Category = []string{"207Q00000X", "207RP1001X", "207X00000X", "261QP1100X"}
	sourceDef.Aliases = []string{"COLLOM AND CARNEY CLINIC", "COLLOM AND CARNEY CLINIC COLLEGE DRIVE", "COLLOM AND CARNEY CLINIC ORTHOPEDICS", "COLLOM AND CARNEY CLINIC PULMONOLOGY"}
	sourceDef.Identifiers = map[string][]string{"http://hl7.org/fhir/sid/us-npi": []string{"1083696801", "1285061648", "1346222171"}}
	sourceDef.BrandLogo = "collom-and-carney-clinic.svg"
	sourceDef.PatientAccessUrl = "https://www.cccahealth.com/"
	sourceDef.SecretKeyPrefix = "nextgen"

	return sourceDef, err
}
