// Copyright (C) Fasten Health, Inc. - All Rights Reserved.
//
// THIS FILE IS GENERATED BY https://github.com/fastenhealth/fasten-sources-gen
// PLEASE DO NOT EDIT BY HAND

package source

import (
	platform "github.com/fastenhealth/fasten-sources/definitions/internal/platform"
	models "github.com/fastenhealth/fasten-sources/definitions/models"
	pkg "github.com/fastenhealth/fasten-sources/pkg"
)

// https://edhwebportal.hitchcock.org/FHIRProxy/api/FHIR/R4/.well-known/smart-configuration
// https://edhwebportal.hitchcock.org/FHIRProxy/api/FHIR/R4/metadata
func GetSourceDartmouthHitchcock(env pkg.FastenLighthouseEnvType) (models.LighthouseSourceDefinition, error) {
	sourceDef, err := platform.GetSourceEpic(env)
	sourceDef.AuthorizationEndpoint = "https://edhwebportal.hitchcock.org/FHIRProxy/oauth2/authorize"
	sourceDef.TokenEndpoint = "https://edhwebportal.hitchcock.org/FHIRProxy/oauth2/token"

	sourceDef.Audience = "https://edhwebportal.hitchcock.org/FHIRProxy/api/FHIR/R4"

	sourceDef.ApiEndpointBaseUrl = "https://edhwebportal.hitchcock.org/FHIRProxy/api/FHIR/R4"
	sourceDef.RedirectUri = pkg.GetCallbackEndpoint(string(pkg.SourceTypeEpic))

	sourceDef.Display = "Dartmouth-Hitchcock"
	sourceDef.SourceType = pkg.SourceTypeDartmouthHitchcock
	sourceDef.SecretKeyPrefix = "epic"

	return sourceDef, err
}
