// Copyright (C) Fasten Health, Inc. - All Rights Reserved.
//
// THIS FILE IS GENERATED BY https://github.com/fastenhealth/fasten-sources-gen
// PLEASE DO NOT EDIT BY HAND

package source

import (
	platform "github.com/fastenhealth/fasten-sources/definitions/internal/platform"
	models "github.com/fastenhealth/fasten-sources/definitions/models"
	pkg "github.com/fastenhealth/fasten-sources/pkg"
)

// https://fhir-myrecord.cerner.com/r4/1Dszw2goTz-HRPQAjnp5h-SWxEe2-Tfi/metadata
func GetSourceDavidLCrowderMDInc(env pkg.FastenLighthouseEnvType, clientIdLookup map[pkg.SourceType]string) (models.LighthouseSourceDefinition, error) {
	sourceDef, err := platform.GetSourceCerner(env, clientIdLookup)
	sourceDef.AuthorizationEndpoint = "https://authorization.cerner.com/tenants/1Dszw2goTz-HRPQAjnp5h-SWxEe2-Tfi/protocols/oauth2/profiles/smart-v1/personas/patient/authorize"
	sourceDef.TokenEndpoint = "https://authorization.cerner.com/tenants/1Dszw2goTz-HRPQAjnp5h-SWxEe2-Tfi/protocols/oauth2/profiles/smart-v1/token"
	sourceDef.IntrospectionEndpoint = "https://authorization.cerner.com/tokeninfo"

	sourceDef.Audience = "https://fhir-myrecord.cerner.com/r4/1Dszw2goTz-HRPQAjnp5h-SWxEe2-Tfi"

	sourceDef.ApiEndpointBaseUrl = "https://fhir-myrecord.cerner.com/r4/1Dszw2goTz-HRPQAjnp5h-SWxEe2-Tfi"
	// retrieve client-id, if available
	if clientId, clientIdOk := clientIdLookup[pkg.SourceTypeDavidLCrowderMDInc]; clientIdOk {
		sourceDef.ClientId = clientId
	}
	sourceDef.RedirectUri = pkg.GetCallbackEndpoint(string(pkg.SourceTypeCerner))

	sourceDef.Display = "David L. Crowder, M.D., Inc"
	sourceDef.SourceType = pkg.SourceTypeDavidLCrowderMDInc
	sourceDef.PatientAccessUrl = "https://cullmanregional.com/doctor/david-crowder/"
	sourceDef.SecretKeyPrefix = "cerner"

	return sourceDef, err
}
