// Copyright (C) Fasten Health, Inc. - All Rights Reserved.
//
// THIS FILE IS GENERATED BY https://github.com/fastenhealth/fasten-sources-gen
// PLEASE DO NOT EDIT BY HAND

package source

import (
	platform "github.com/fastenhealth/fasten-sources/definitions/internal/platform"
	models "github.com/fastenhealth/fasten-sources/definitions/models"
	pkg "github.com/fastenhealth/fasten-sources/pkg"
)

// https://epicproxy.et1073.epichosted.com/FHIRProxy/api/FHIR/R4/metadata
func GetSourceEnglewoodHospitalAndMedicalCenter(env pkg.FastenLighthouseEnvType, clientIdLookup map[pkg.SourceType]string) (models.LighthouseSourceDefinition, error) {
	sourceDef, err := platform.GetSourceEpic(env, clientIdLookup)
	sourceDef.AuthorizationEndpoint = "https://epicproxy.et1073.epichosted.com/FHIRProxy/oauth2/authorize"
	sourceDef.TokenEndpoint = "https://epicproxy.et1073.epichosted.com/FHIRProxy/oauth2/token"
	sourceDef.RegistrationEndpoint = "https://epicproxy.et1073.epichosted.com/FHIRProxy/oauth2/register"

	sourceDef.Audience = "https://epicproxy.et1073.epichosted.com/FHIRProxy/api/FHIR/R4"

	sourceDef.ApiEndpointBaseUrl = "https://epicproxy.et1073.epichosted.com/FHIRProxy/api/FHIR/R4"
	// retrieve client-id, if available
	if clientId, clientIdOk := clientIdLookup[pkg.SourceTypeEnglewoodHospitalAndMedicalCenter]; clientIdOk {
		sourceDef.ClientId = clientId
	}
	sourceDef.RedirectUri = pkg.GetCallbackEndpoint(string(pkg.SourceTypeEpic))

	sourceDef.Display = "Englewood Hospital and Medical Center"
	sourceDef.SourceType = pkg.SourceTypeEnglewoodHospitalAndMedicalCenter
	sourceDef.Category = []string{"261QS1000X", "273R00000X", "282N00000X"}
	sourceDef.Aliases = []string{}
	sourceDef.Identifiers = map[string][]string{"http://hl7.org/fhir/sid/us-npi": []string{"1083612881", "1124071980", "1487903456", "1720325038", "1992089429"}}
	sourceDef.SecretKeyPrefix = "epic"

	return sourceDef, err
}
