// Copyright (C) Fasten Health, Inc. - All Rights Reserved.
//
// THIS FILE IS GENERATED BY https://github.com/fastenhealth/fasten-sources-gen
// PLEASE DO NOT EDIT BY HAND

package source

import (
	platform "github.com/fastenhealth/fasten-sources/definitions/internal/platform"
	models "github.com/fastenhealth/fasten-sources/definitions/models"
	pkg "github.com/fastenhealth/fasten-sources/pkg"
)

// https://epicserviceGW.froedtert.com/FHIRProxyPRD/api/FHIR/R4/.well-known/smart-configuration
// https://epicserviceGW.froedtert.com/FHIRProxyPRD/api/FHIR/R4/metadata
func GetSourceFroedtertHealth(env pkg.FastenLighthouseEnvType) (models.LighthouseSourceDefinition, error) {
	sourceDef, err := platform.GetSourceEpic(env)
	sourceDef.AuthorizationEndpoint = "https://epicservicegw.froedtert.com/FHIRproxyPRD/oauth2/authorize"
	sourceDef.TokenEndpoint = "https://epicservicegw.froedtert.com/FHIRproxyPRD/oauth2/token"

	sourceDef.Audience = "https://epicserviceGW.froedtert.com/FHIRProxyPRD/api/FHIR/R4"

	sourceDef.ApiEndpointBaseUrl = "https://epicserviceGW.froedtert.com/FHIRProxyPRD/api/FHIR/R4"
	sourceDef.RedirectUri = pkg.GetCallbackEndpoint(string(pkg.SourceTypeEpic))

	sourceDef.Display = "Froedtert Health"
	sourceDef.SourceType = pkg.SourceTypeFroedtertHealth
	sourceDef.SecretKeyPrefix = "epic"

	return sourceDef, err
}
