// Copyright (C) Fasten Health, Inc. - All Rights Reserved.
//
// THIS FILE IS GENERATED BY https://github.com/fastenhealth/fasten-sources-gen
// PLEASE DO NOT EDIT BY HAND

package source

import (
	platform "github.com/fastenhealth/fasten-sources/definitions/internal/platform"
	models "github.com/fastenhealth/fasten-sources/definitions/models"
	pkg "github.com/fastenhealth/fasten-sources/pkg"
)

// https://fhir.jtdmh.org/R4/open-Prod/metadata
func GetSourceGl01(env pkg.FastenLighthouseEnvType, clientIdLookup map[pkg.SourceType]string) (models.LighthouseSourceDefinition, error) {
	sourceDef, err := platform.GetSourceAllscripts(env, clientIdLookup)
	sourceDef.AuthorizationEndpoint = "https://global.open.allscripts.com/fhirroute/fmhpatientauth/fmhorgid/8db9215b-8688-484c-a396-a5f700884e0d/connect/authorize"
	sourceDef.TokenEndpoint = "https://global.open.allscripts.com/fhirroute/fmhpatientauth/fmhorgid/8db9215b-8688-484c-a396-a5f700884e0d/connect/token"

	sourceDef.Audience = "https://fhir.jtdmh.org/R4/open-Prod"

	sourceDef.ApiEndpointBaseUrl = "https://fhir.jtdmh.org/R4/open-Prod"
	// retrieve client-id, if available
	if clientId, clientIdOk := clientIdLookup[pkg.SourceTypeGl01]; clientIdOk {
		sourceDef.ClientId = clientId
	}
	sourceDef.RedirectUri = pkg.GetCallbackEndpoint(string(pkg.SourceTypeAllscripts))

	sourceDef.Display = "GL0"
	sourceDef.SourceType = pkg.SourceTypeGl01
	sourceDef.Category = []string{}
	sourceDef.Aliases = []string{}
	sourceDef.SecretKeyPrefix = "allscripts"

	return sourceDef, err
}
