// Copyright (C) Fasten Health, Inc. - All Rights Reserved.
//
// THIS FILE IS GENERATED BY https://github.com/fastenhealth/fasten-sources-gen
// PLEASE DO NOT EDIT BY HAND

package source

import (
	platform "github.com/fastenhealth/fasten-sources/definitions/internal/platform"
	models "github.com/fastenhealth/fasten-sources/definitions/models"
	pkg "github.com/fastenhealth/fasten-sources/pkg"
)

// https://fhir-myrecord.cerner.com/r4/33781e48-45d8-4dd5-8e8e-25f1504575df/.well-known/smart-configuration
// https://fhir-myrecord.cerner.com/r4/33781e48-45d8-4dd5-8e8e-25f1504575df/metadata
func GetSourceInstitutoMedicalSanNicolasImsan(env pkg.FastenLighthouseEnvType) (models.LighthouseSourceDefinition, error) {
	sourceDef, err := platform.GetSourceCerner(env)
	sourceDef.AuthorizationEndpoint = "https://authorization.cerner.com/tenants/33781e48-45d8-4dd5-8e8e-25f1504575df/protocols/oauth2/profiles/smart-v1/personas/patient/authorize"
	sourceDef.TokenEndpoint = "https://authorization.cerner.com/tenants/33781e48-45d8-4dd5-8e8e-25f1504575df/protocols/oauth2/profiles/smart-v1/token"
	sourceDef.IntrospectionEndpoint = "https://authorization.cerner.com/tokeninfo"

	sourceDef.Audience = "https://fhir-myrecord.cerner.com/r4/33781e48-45d8-4dd5-8e8e-25f1504575df"

	sourceDef.ApiEndpointBaseUrl = "https://fhir-myrecord.cerner.com/r4/33781e48-45d8-4dd5-8e8e-25f1504575df"
	sourceDef.RedirectUri = pkg.GetCallbackEndpoint(string(pkg.SourceTypeCerner))

	sourceDef.Display = "Instituto Medical San Nicolas (IMSAN)"
	sourceDef.SourceType = pkg.SourceTypeInstitutoMedicalSanNicolasImsan
	sourceDef.Hidden = true
	sourceDef.SecretKeyPrefix = "cerner"

	return sourceDef, err
}
