// Copyright (C) Fasten Health, Inc. - All Rights Reserved.
//
// THIS FILE IS GENERATED BY https://github.com/fastenhealth/fasten-sources-gen
// PLEASE DO NOT EDIT BY HAND

package source

import (
	platform "github.com/fastenhealth/fasten-sources/definitions/internal/platform"
	models "github.com/fastenhealth/fasten-sources/definitions/models"
	pkg "github.com/fastenhealth/fasten-sources/pkg"
)

// https://fhir-myrecord.cerner.com/r4/48b0ed26-b687-4cf9-9aa1-7924cd98c950/metadata
func GetSourceKernCountyHospitalAuthority(env pkg.FastenLighthouseEnvType, clientIdLookup map[pkg.SourceType]string) (models.LighthouseSourceDefinition, error) {
	sourceDef, err := platform.GetSourceCerner(env, clientIdLookup)
	sourceDef.AuthorizationEndpoint = "https://authorization.cerner.com/tenants/48b0ed26-b687-4cf9-9aa1-7924cd98c950/protocols/oauth2/profiles/smart-v1/personas/patient/authorize"
	sourceDef.TokenEndpoint = "https://authorization.cerner.com/tenants/48b0ed26-b687-4cf9-9aa1-7924cd98c950/protocols/oauth2/profiles/smart-v1/token"
	sourceDef.IntrospectionEndpoint = "https://authorization.cerner.com/tokeninfo"

	sourceDef.Audience = "https://fhir-myrecord.cerner.com/r4/48b0ed26-b687-4cf9-9aa1-7924cd98c950"

	sourceDef.ApiEndpointBaseUrl = "https://fhir-myrecord.cerner.com/r4/48b0ed26-b687-4cf9-9aa1-7924cd98c950"
	// retrieve client-id, if available
	if clientId, clientIdOk := clientIdLookup[pkg.SourceTypeKernCountyHospitalAuthority]; clientIdOk {
		sourceDef.ClientId = clientId
	}
	sourceDef.RedirectUri = pkg.GetCallbackEndpoint(string(pkg.SourceTypeCerner))

	sourceDef.Display = "Kern County Hospital Authority"
	sourceDef.SourceType = pkg.SourceTypeKernCountyHospitalAuthority
	sourceDef.Category = []string{"208D00000X", "282N00000X", "385H00000X", "333600000X"}
	sourceDef.Aliases = []string{"KERN MEDICAL", "KERN MEDICAL CENTER"}
	sourceDef.Identifiers = map[string][]string{"http://hl7.org/fhir/sid/us-npi": []string{"1629784087", "1699282285", "1336668284", "1770124976", "1376960005", "1093243255", "1427176569", "1699859223", "1164974739", "1538611967"}}
	sourceDef.PatientAccessUrl = "https://www.kernmedical.com/locations/hospital/"
	sourceDef.SecretKeyPrefix = "cerner"

	return sourceDef, err
}
