// Copyright (C) Fasten Health, Inc. - All Rights Reserved.
//
// THIS FILE IS GENERATED BY https://github.com/fastenhealth/fasten-sources-gen
// PLEASE DO NOT EDIT BY HAND

package source

import (
	platform "github.com/fastenhealth/fasten-sources/definitions/internal/platform"
	models "github.com/fastenhealth/fasten-sources/definitions/models"
	pkg "github.com/fastenhealth/fasten-sources/pkg"
)

// https://fhir-myrecord.cerner.com/r4/6f9e2eb1-49bb-4863-9a96-e4549126af91/metadata
func GetSourceKiowaCountyMemorialHospital(env pkg.FastenLighthouseEnvType, clientIdLookup map[pkg.SourceType]string) (models.LighthouseSourceDefinition, error) {
	sourceDef, err := platform.GetSourceCerner(env, clientIdLookup)
	sourceDef.AuthorizationEndpoint = "https://authorization.cerner.com/tenants/6f9e2eb1-49bb-4863-9a96-e4549126af91/protocols/oauth2/profiles/smart-v1/personas/patient/authorize"
	sourceDef.TokenEndpoint = "https://authorization.cerner.com/tenants/6f9e2eb1-49bb-4863-9a96-e4549126af91/protocols/oauth2/profiles/smart-v1/token"
	sourceDef.IntrospectionEndpoint = "https://authorization.cerner.com/tokeninfo"

	sourceDef.Audience = "https://fhir-myrecord.cerner.com/r4/6f9e2eb1-49bb-4863-9a96-e4549126af91"

	sourceDef.ApiEndpointBaseUrl = "https://fhir-myrecord.cerner.com/r4/6f9e2eb1-49bb-4863-9a96-e4549126af91"
	// retrieve client-id, if available
	if clientId, clientIdOk := clientIdLookup[pkg.SourceTypeKiowaCountyMemorialHospital]; clientIdOk {
		sourceDef.ClientId = clientId
	}
	sourceDef.RedirectUri = pkg.GetCallbackEndpoint(string(pkg.SourceTypeCerner))

	sourceDef.Display = "Kiowa County Memorial Hospital"
	sourceDef.SourceType = pkg.SourceTypeKiowaCountyMemorialHospital
	sourceDef.Category = []string{"208000000X", "363A00000X", "261QR1300X", "208D00000X", "282NC0060X", "275N00000X", "341600000X", "261QP2300X"}
	sourceDef.Aliases = []string{"GREENSBURG FAMILY PRACTICE", "GREENSBURG FAMILY PRACTICE (NON RHC)", "KIOWA COUNTY MEMORIAL HOSPITA-SSB", "KIOWA COUNTY MEMORIAL HOSPITAL"}
	sourceDef.Identifiers = map[string][]string{"http://hl7.org/fhir/sid/us-npi": []string{"1417901927", "1831431030", "1538776299", "1952406514", "1942309166", "1063009819"}}
	sourceDef.BrandLogo = "kiowa-county-memorial-hospital.jpg"
	sourceDef.PatientAccessUrl = "https://kcmh.net/"
	sourceDef.SecretKeyPrefix = "cerner"

	return sourceDef, err
}
