// Copyright (C) Fasten Health, Inc. - All Rights Reserved.
//
// THIS FILE IS GENERATED BY https://github.com/fastenhealth/fasten-sources-gen
// PLEASE DO NOT EDIT BY HAND

package source

import (
	platform "github.com/fastenhealth/fasten-sources/definitions/internal/platform"
	models "github.com/fastenhealth/fasten-sources/definitions/models"
	pkg "github.com/fastenhealth/fasten-sources/pkg"
)

// https://fhir-myrecord.cerner.com/r4/kTOm84ioLtLtc7IhordnWeQQC_oGyQ8b/metadata
func GetSourceLafayetteFamilyFootcare(env pkg.FastenLighthouseEnvType, clientIdLookup map[pkg.SourceType]string) (models.LighthouseSourceDefinition, error) {
	sourceDef, err := platform.GetSourceCerner(env, clientIdLookup)
	sourceDef.AuthorizationEndpoint = "https://authorization.cerner.com/tenants/kTOm84ioLtLtc7IhordnWeQQC_oGyQ8b/protocols/oauth2/profiles/smart-v1/personas/patient/authorize"
	sourceDef.TokenEndpoint = "https://authorization.cerner.com/tenants/kTOm84ioLtLtc7IhordnWeQQC_oGyQ8b/protocols/oauth2/profiles/smart-v1/token"
	sourceDef.IntrospectionEndpoint = "https://authorization.cerner.com/tokeninfo"

	sourceDef.Audience = "https://fhir-myrecord.cerner.com/r4/kTOm84ioLtLtc7IhordnWeQQC_oGyQ8b"

	sourceDef.ApiEndpointBaseUrl = "https://fhir-myrecord.cerner.com/r4/kTOm84ioLtLtc7IhordnWeQQC_oGyQ8b"
	// retrieve client-id, if available
	if clientId, clientIdOk := clientIdLookup[pkg.SourceTypeLafayetteFamilyFootcare]; clientIdOk {
		sourceDef.ClientId = clientId
	}
	sourceDef.RedirectUri = pkg.GetCallbackEndpoint(string(pkg.SourceTypeCerner))

	sourceDef.Display = "Lafayette Family Footcare"
	sourceDef.SourceType = pkg.SourceTypeLafayetteFamilyFootcare
	sourceDef.PatientAccessUrl = "https://doctor.webmd.com/practice/lafayette-family-foot-care-0f8f8af8-f126-e311-a62b-001f29e3eb44"
	sourceDef.SecretKeyPrefix = "cerner"

	return sourceDef, err
}
