// Copyright (C) Fasten Health, Inc. - All Rights Reserved.
//
// THIS FILE IS GENERATED BY https://github.com/fastenhealth/fasten-sources-gen
// PLEASE DO NOT EDIT BY HAND

package source

import (
	platform "github.com/fastenhealth/fasten-sources/definitions/internal/platform"
	models "github.com/fastenhealth/fasten-sources/definitions/models"
	pkg "github.com/fastenhealth/fasten-sources/pkg"
)

// https://fhir-myrecord.cerner.com/r4/3ed7024d-31b1-4539-9702-b0342e4213ca/.well-known/smart-configuration
// https://fhir-myrecord.cerner.com/r4/3ed7024d-31b1-4539-9702-b0342e4213ca/metadata
func GetSourceMcphersonMedicalAndSurgicalAssociates(env pkg.FastenLighthouseEnvType) (models.LighthouseSourceDefinition, error) {
	sourceDef, err := platform.GetSourceCerner(env)
	sourceDef.AuthorizationEndpoint = "https://authorization.cerner.com/tenants/3ed7024d-31b1-4539-9702-b0342e4213ca/protocols/oauth2/profiles/smart-v1/personas/patient/authorize"
	sourceDef.TokenEndpoint = "https://authorization.cerner.com/tenants/3ed7024d-31b1-4539-9702-b0342e4213ca/protocols/oauth2/profiles/smart-v1/token"
	sourceDef.IntrospectionEndpoint = "https://authorization.cerner.com/tokeninfo"

	sourceDef.Audience = "https://fhir-myrecord.cerner.com/r4/3ed7024d-31b1-4539-9702-b0342e4213ca"

	sourceDef.ApiEndpointBaseUrl = "https://fhir-myrecord.cerner.com/r4/3ed7024d-31b1-4539-9702-b0342e4213ca"
	sourceDef.RedirectUri = pkg.GetCallbackEndpoint(string(pkg.SourceTypeCerner))

	sourceDef.Display = "McPherson Medical and Surgical Associates"
	sourceDef.SourceType = pkg.SourceTypeMcphersonMedicalAndSurgicalAssociates
	sourceDef.Hidden = true
	sourceDef.SecretKeyPrefix = "cerner"

	return sourceDef, err
}
