// Copyright (C) Fasten Health, Inc. - All Rights Reserved.
//
// THIS FILE IS GENERATED BY https://github.com/fastenhealth/fasten-sources-gen
// PLEASE DO NOT EDIT BY HAND

package source

import (
	platform "github.com/fastenhealth/fasten-sources/definitions/internal/platform"
	models "github.com/fastenhealth/fasten-sources/definitions/models"
	pkg "github.com/fastenhealth/fasten-sources/pkg"
)

// https://fhir.nextgen.com/nge/prod/fhir-api-r4/fhir/r4/metadata
func GetSourceMelbourneMaternalFetalMedicine(env pkg.FastenLighthouseEnvType, clientIdLookup map[pkg.SourceType]string) (models.LighthouseSourceDefinition, error) {
	sourceDef, err := platform.GetSourceNextgen(env, clientIdLookup)
	sourceDef.AuthorizationEndpoint = "https://fhir.nextgen.com/nge/prod/patient-oauth/authorize"
	sourceDef.TokenEndpoint = "https://fhir.nextgen.com/nge/prod/patient-oauth/token"

	sourceDef.Audience = "https://fhir.nextgen.com/nge/prod/fhir-api-r4/fhir/r4"

	sourceDef.ApiEndpointBaseUrl = "https://fhir.nextgen.com/nge/prod/fhir-api-r4/fhir/r4"
	// retrieve client-id, if available
	if clientId, clientIdOk := clientIdLookup[pkg.SourceTypeMelbourneMaternalFetalMedicine]; clientIdOk {
		sourceDef.ClientId = clientId
	}
	sourceDef.RedirectUri = pkg.GetCallbackEndpoint(string(pkg.SourceTypeNextgen))

	sourceDef.Display = "Melbourne Maternal Fetal Medicine"
	sourceDef.SourceType = pkg.SourceTypeMelbourneMaternalFetalMedicine
	sourceDef.PatientAccessUrl = "https://www.mturkcontent.com/dynamic/hit?assignmentId=3XXU1SWE80S9F5V4L23L60O629TA0Z&hitId=30Y6N4AHZ2TTRMKL9N81RD1AL0JDR0&workerId=AP60PDVGXST1D&turkSubmitTo=https%3A%2F%2Fwww.mturk.com#:~:text=%22https%3A//healthcare.example.com%22%20required"
	sourceDef.SecretKeyPrefix = "nextgen"

	return sourceDef, err
}
