// Copyright (C) Fasten Health, Inc. - All Rights Reserved.
//
// THIS FILE IS GENERATED BY https://github.com/fastenhealth/fasten-sources-gen
// PLEASE DO NOT EDIT BY HAND

package source

import (
	platform "github.com/fastenhealth/fasten-sources/definitions/internal/platform"
	models "github.com/fastenhealth/fasten-sources/definitions/models"
	pkg "github.com/fastenhealth/fasten-sources/pkg"
)

// https://fhir.nextgen.com/nge/prod/fhir-api-r4/fhir/r4/metadata
func GetSourceMercyMedicalServices(env pkg.FastenLighthouseEnvType, clientIdLookup map[pkg.SourceType]string) (models.LighthouseSourceDefinition, error) {
	sourceDef, err := platform.GetSourceNextgen(env, clientIdLookup)
	sourceDef.AuthorizationEndpoint = "https://fhir.nextgen.com/nge/prod/patient-oauth/authorize"
	sourceDef.TokenEndpoint = "https://fhir.nextgen.com/nge/prod/patient-oauth/token"

	sourceDef.Audience = "https://fhir.nextgen.com/nge/prod/fhir-api-r4/fhir/r4"

	sourceDef.ApiEndpointBaseUrl = "https://fhir.nextgen.com/nge/prod/fhir-api-r4/fhir/r4"
	// retrieve client-id, if available
	if clientId, clientIdOk := clientIdLookup[pkg.SourceTypeMercyMedicalServices]; clientIdOk {
		sourceDef.ClientId = clientId
	}
	sourceDef.RedirectUri = pkg.GetCallbackEndpoint(string(pkg.SourceTypeNextgen))

	sourceDef.Display = "Mercy Medical Services"
	sourceDef.SourceType = pkg.SourceTypeMercyMedicalServices
	sourceDef.Category = []string{"207Q00000X", "207R00000X", "261QR1300X", "363AM0700X", "363L00000X", "363LF0000X", "363LP0808X"}
	sourceDef.Aliases = []string{"MERCY INTERNAL MEDICINE", "MERCYONE AKRON FAMILY MEDICINE", "MERCYONE INTERNAL MEDICINE CLINIC", "MERCYONE KINGSLEY FAMILY MEDICINE", "MERCYONE PONCA FAMILY MEDICINE", "MERCYONE SOUTH SIOUX FAMILY MEDICINE", "PONCA MERCY MEDICAL CLINIC"}
	sourceDef.Identifiers = map[string][]string{"http://hl7.org/fhir/sid/us-npi": []string{"1043251754", "1083652218", "1093966244", "1215978929", "1255479143", "1710925813", "1720026461", "1790723633", "1831139328", "1902840671"}}
	sourceDef.SecretKeyPrefix = "nextgen"

	return sourceDef, err
}
