// Copyright (C) Fasten Health, Inc. - All Rights Reserved.
//
// THIS FILE IS GENERATED BY https://github.com/fastenhealth/fasten-sources-gen
// PLEASE DO NOT EDIT BY HAND

package source

import (
	platform "github.com/fastenhealth/fasten-sources/definitions/internal/platform"
	models "github.com/fastenhealth/fasten-sources/definitions/models"
	pkg "github.com/fastenhealth/fasten-sources/pkg"
)

// https://chperx.health-partners.org/Proxy-FHIR/api/FHIR/R4/.well-known/smart-configuration
// https://chperx.health-partners.org/Proxy-FHIR/api/FHIR/R4/metadata
func GetSourceMercyHealthOhKy(env pkg.FastenEnvType) (models.LighthouseSourceDefinition, error) {
	sourceDef, err := platform.GetSourceEpic(env)
	sourceDef.AuthorizationEndpoint = "https://carepath.health-partners.org/Proxy-FHIR/oauth2/authorize"
	sourceDef.TokenEndpoint = "https://carepath.health-partners.org/Proxy-FHIR/oauth2/token"

	sourceDef.Audience = "https://chperx.health-partners.org/Proxy-FHIR/api/FHIR/R4"

	sourceDef.ApiEndpointBaseUrl = "https://chperx.health-partners.org/Proxy-FHIR/api/FHIR/R4"
	if env == pkg.FastenEnvSandbox {
		sourceDef.ClientId = ""
	}
	sourceDef.RedirectUri = pkg.GetCallbackEndpoint(string(pkg.SourceTypeEpic))

	sourceDef.Display = "Mercy Health - OH, KY"
	sourceDef.SourceType = pkg.SourceTypeMercyHealthOhKy
	sourceDef.Enabled = true
	sourceDef.SecretKeyPrefix = "epic"

	return sourceDef, err
}
