// Copyright (C) Fasten Health, Inc. - All Rights Reserved.
//
// THIS FILE IS GENERATED BY https://github.com/fastenhealth/fasten-sources-gen
// PLEASE DO NOT EDIT BY HAND

package source

import (
	platform "github.com/fastenhealth/fasten-sources/definitions/internal/platform"
	models "github.com/fastenhealth/fasten-sources/definitions/models"
	pkg "github.com/fastenhealth/fasten-sources/pkg"
)

// https://fhir-myrecord.cerner.com/r4/657e1fae-2721-4373-98ee-a5ae763a6e77/metadata
func GetSourceMercyMedicalCenterNewHampton(env pkg.FastenLighthouseEnvType, clientIdLookup map[pkg.SourceType]string) (models.LighthouseSourceDefinition, error) {
	sourceDef, err := platform.GetSourceCerner(env, clientIdLookup)
	sourceDef.AuthorizationEndpoint = "https://authorization.cerner.com/tenants/657e1fae-2721-4373-98ee-a5ae763a6e77/protocols/oauth2/profiles/smart-v1/personas/patient/authorize"
	sourceDef.TokenEndpoint = "https://authorization.cerner.com/tenants/657e1fae-2721-4373-98ee-a5ae763a6e77/protocols/oauth2/profiles/smart-v1/token"
	sourceDef.IntrospectionEndpoint = "https://authorization.cerner.com/tokeninfo"

	sourceDef.Audience = "https://fhir-myrecord.cerner.com/r4/657e1fae-2721-4373-98ee-a5ae763a6e77"

	sourceDef.ApiEndpointBaseUrl = "https://fhir-myrecord.cerner.com/r4/657e1fae-2721-4373-98ee-a5ae763a6e77"
	// retrieve client-id, if available
	if clientId, clientIdOk := clientIdLookup[pkg.SourceTypeMercyMedicalCenterNewHampton]; clientIdOk {
		sourceDef.ClientId = clientId
	}
	sourceDef.RedirectUri = pkg.GetCallbackEndpoint(string(pkg.SourceTypeCerner))

	sourceDef.Display = "Mercy Medical Center-New Hampton"
	sourceDef.SourceType = pkg.SourceTypeMercyMedicalCenterNewHampton
	sourceDef.Category = []string{"367500000X"}
	sourceDef.Aliases = []string{"MERCYONE NEW HAMPTON MEDICAL CENTER-CRNA"}
	sourceDef.Identifiers = map[string][]string{"http://hl7.org/fhir/sid/us-npi": []string{"1093986093"}}
	sourceDef.BrandLogo = "mercy-medical-center-new-hampton.jpg"
	sourceDef.PatientAccessUrl = "https://www.mercyone.org/"
	sourceDef.SecretKeyPrefix = "cerner"

	return sourceDef, err
}
