// Copyright (C) Fasten Health, Inc. - All Rights Reserved.
//
// THIS FILE IS GENERATED BY https://github.com/fastenhealth/fasten-sources-gen
// PLEASE DO NOT EDIT BY HAND

package source

import (
	platform "github.com/fastenhealth/fasten-sources/definitions/internal/platform"
	models "github.com/fastenhealth/fasten-sources/definitions/models"
	pkg "github.com/fastenhealth/fasten-sources/pkg"
)

// https://fhir-myrecord.cerner.com/r4/41e7ed61-011a-4b3f-8e27-7aa832467b04/metadata
func GetSourceMonongaliaCountyGeneralHospitalCompany(env pkg.FastenLighthouseEnvType, clientIdLookup map[pkg.SourceType]string) (models.LighthouseSourceDefinition, error) {
	sourceDef, err := platform.GetSourceCerner(env, clientIdLookup)
	sourceDef.AuthorizationEndpoint = "https://authorization.cerner.com/tenants/41e7ed61-011a-4b3f-8e27-7aa832467b04/protocols/oauth2/profiles/smart-v1/personas/patient/authorize"
	sourceDef.TokenEndpoint = "https://authorization.cerner.com/tenants/41e7ed61-011a-4b3f-8e27-7aa832467b04/protocols/oauth2/profiles/smart-v1/token"
	sourceDef.IntrospectionEndpoint = "https://authorization.cerner.com/tokeninfo"

	sourceDef.Audience = "https://fhir-myrecord.cerner.com/r4/41e7ed61-011a-4b3f-8e27-7aa832467b04"

	sourceDef.ApiEndpointBaseUrl = "https://fhir-myrecord.cerner.com/r4/41e7ed61-011a-4b3f-8e27-7aa832467b04"
	// retrieve client-id, if available
	if clientId, clientIdOk := clientIdLookup[pkg.SourceTypeMonongaliaCountyGeneralHospitalCompany]; clientIdOk {
		sourceDef.ClientId = clientId
	}
	sourceDef.RedirectUri = pkg.GetCallbackEndpoint(string(pkg.SourceTypeCerner))

	sourceDef.Display = "Monongalia County General Hospital Company"
	sourceDef.SourceType = pkg.SourceTypeMonongaliaCountyGeneralHospitalCompany
	sourceDef.PatientAccessUrl = "https://www.monhealth.com"
	sourceDef.SecretKeyPrefix = "cerner"

	return sourceDef, err
}
