// Copyright (C) Fasten Health, Inc. - All Rights Reserved.
//
// THIS FILE IS GENERATED BY https://github.com/fastenhealth/fasten-sources-gen
// PLEASE DO NOT EDIT BY HAND

package source

import (
	platform "github.com/fastenhealth/fasten-sources/definitions/internal/platform"
	models "github.com/fastenhealth/fasten-sources/definitions/models"
	pkg "github.com/fastenhealth/fasten-sources/pkg"
)

// https://fhir-myrecord.cerner.com/r4/c6612efa-63ce-4f4e-a3d7-9d31c013cadb/metadata
func GetSourceMontefioreMedicalCenter1(env pkg.FastenLighthouseEnvType, clientIdLookup map[pkg.SourceType]string) (models.LighthouseSourceDefinition, error) {
	sourceDef, err := platform.GetSourceCerner(env, clientIdLookup)
	sourceDef.AuthorizationEndpoint = "https://authorization.cerner.com/tenants/c6612efa-63ce-4f4e-a3d7-9d31c013cadb/protocols/oauth2/profiles/smart-v1/personas/patient/authorize"
	sourceDef.TokenEndpoint = "https://authorization.cerner.com/tenants/c6612efa-63ce-4f4e-a3d7-9d31c013cadb/protocols/oauth2/profiles/smart-v1/token"
	sourceDef.IntrospectionEndpoint = "https://authorization.cerner.com/tokeninfo"

	sourceDef.Audience = "https://fhir-myrecord.cerner.com/r4/c6612efa-63ce-4f4e-a3d7-9d31c013cadb"

	sourceDef.ApiEndpointBaseUrl = "https://fhir-myrecord.cerner.com/r4/c6612efa-63ce-4f4e-a3d7-9d31c013cadb"
	// retrieve client-id, if available
	if clientId, clientIdOk := clientIdLookup[pkg.SourceTypeMontefioreMedicalCenter1]; clientIdOk {
		sourceDef.ClientId = clientId
	}
	sourceDef.RedirectUri = pkg.GetCallbackEndpoint(string(pkg.SourceTypeCerner))

	sourceDef.Display = "Montefiore Medical Center"
	sourceDef.SourceType = pkg.SourceTypeMontefioreMedicalCenter1
	sourceDef.Category = []string{"261QP2300X", "282N00000X", "1223E0200X", "1223P0221X", "1223S0112X", "122300000X", "261QM1300X"}
	sourceDef.Identifiers = map[string][]string{"http://hl7.org/fhir/sid/us-npi": []string{"1255568838", "1255565925", "1790974897", "1326232042", "1275710519", "1487848156", "1740446624", "1659537538", "1982860953", "1750528188", "1194981084"}}
	sourceDef.BrandLogo = "montefiore-medical-center.png"
	sourceDef.SecretKeyPrefix = "cerner"

	return sourceDef, err
}
