// Copyright (C) Fasten Health, Inc. - All Rights Reserved.
//
// THIS FILE IS GENERATED BY https://github.com/fastenhealth/fasten-sources-gen
// PLEASE DO NOT EDIT BY HAND

package source

import (
	platform "github.com/fastenhealth/fasten-sources/definitions/internal/platform"
	models "github.com/fastenhealth/fasten-sources/definitions/models"
	pkg "github.com/fastenhealth/fasten-sources/pkg"
)

// https://fhir.nextgen.com/nge/prod/fhir-api-r4/fhir/r4/metadata
func GetSourceNevadaEyePhysicians(env pkg.FastenLighthouseEnvType, clientIdLookup map[pkg.SourceType]string) (models.LighthouseSourceDefinition, error) {
	sourceDef, err := platform.GetSourceNextgen(env, clientIdLookup)
	sourceDef.AuthorizationEndpoint = "https://fhir.nextgen.com/nge/prod/patient-oauth/authorize"
	sourceDef.TokenEndpoint = "https://fhir.nextgen.com/nge/prod/patient-oauth/token"

	sourceDef.Audience = "https://fhir.nextgen.com/nge/prod/fhir-api-r4/fhir/r4"

	sourceDef.ApiEndpointBaseUrl = "https://fhir.nextgen.com/nge/prod/fhir-api-r4/fhir/r4"
	// retrieve client-id, if available
	if clientId, clientIdOk := clientIdLookup[pkg.SourceTypeNevadaEyePhysicians]; clientIdOk {
		sourceDef.ClientId = clientId
	}
	sourceDef.RedirectUri = pkg.GetCallbackEndpoint(string(pkg.SourceTypeNextgen))

	sourceDef.Display = "Nevada Eye Physicians"
	sourceDef.SourceType = pkg.SourceTypeNevadaEyePhysicians
	sourceDef.Category = []string{"152W00000X", "207W00000X", "332B00000X", "207WX0009X", "207WX0107X", "207WX0108X", "207WX0200X"}
	sourceDef.Aliases = []string{"NEVADA EYE PHYSICIANS", "NEW EYES", "RETINA CONSULTANTS OF NEVADA", "SHEPHERD EYE CENTER", "SIERRA NEVADA EYE CENTER"}
	sourceDef.Identifiers = map[string][]string{"http://hl7.org/fhir/sid/us-npi": []string{"1487604054", "1497939102", "1518141969", "1083961262", "1902153174", "1053359489", "1912574898", "1568032522"}}
	sourceDef.PatientAccessUrl = "https://nevadaeyephysicians.com/locations/henderson/"
	sourceDef.SecretKeyPrefix = "nextgen"

	return sourceDef, err
}
