// Copyright (C) Fasten Health, Inc. - All Rights Reserved.
//
// THIS FILE IS GENERATED BY https://github.com/fastenhealth/fasten-sources-gen
// PLEASE DO NOT EDIT BY HAND

package source

import (
	platform "github.com/fastenhealth/fasten-sources/definitions/internal/platform"
	models "github.com/fastenhealth/fasten-sources/definitions/models"
	pkg "github.com/fastenhealth/fasten-sources/pkg"
)

// https://fhir-myrecord.cerner.com/r4/329afbd4-f1aa-4709-b672-086217c311d9/metadata
func GetSourceNewYorkComprehensiveCarePC(env pkg.FastenLighthouseEnvType, clientIdLookup map[pkg.SourceType]string) (models.LighthouseSourceDefinition, error) {
	sourceDef, err := platform.GetSourceCerner(env, clientIdLookup)
	sourceDef.AuthorizationEndpoint = "https://authorization.cerner.com/tenants/329afbd4-f1aa-4709-b672-086217c311d9/protocols/oauth2/profiles/smart-v1/personas/patient/authorize"
	sourceDef.TokenEndpoint = "https://authorization.cerner.com/tenants/329afbd4-f1aa-4709-b672-086217c311d9/protocols/oauth2/profiles/smart-v1/token"
	sourceDef.IntrospectionEndpoint = "https://authorization.cerner.com/tokeninfo"

	sourceDef.Audience = "https://fhir-myrecord.cerner.com/r4/329afbd4-f1aa-4709-b672-086217c311d9"

	sourceDef.ApiEndpointBaseUrl = "https://fhir-myrecord.cerner.com/r4/329afbd4-f1aa-4709-b672-086217c311d9"
	// retrieve client-id, if available
	if clientId, clientIdOk := clientIdLookup[pkg.SourceTypeNewYorkComprehensiveCarePC]; clientIdOk {
		sourceDef.ClientId = clientId
	}
	sourceDef.RedirectUri = pkg.GetCallbackEndpoint(string(pkg.SourceTypeCerner))

	sourceDef.Display = "New York Comprehensive Care P.C."
	sourceDef.SourceType = pkg.SourceTypeNewYorkComprehensiveCarePC
	sourceDef.BrandLogo = "new-york-comprehensive-care-p-c.jpg"
	sourceDef.PatientAccessUrl = "https://newyorkcmc.com/"
	sourceDef.SecretKeyPrefix = "cerner"

	return sourceDef, err
}
