// Copyright (C) Fasten Health, Inc. - All Rights Reserved.
//
// THIS FILE IS GENERATED BY https://github.com/fastenhealth/fasten-sources-gen
// PLEASE DO NOT EDIT BY HAND

package source

import (
	platform "github.com/fastenhealth/fasten-sources/definitions/internal/platform"
	models "github.com/fastenhealth/fasten-sources/definitions/models"
	pkg "github.com/fastenhealth/fasten-sources/pkg"
)

// https://fhir01.northwell.edu/open/metadata
func GetSourceNorDev013(env pkg.FastenLighthouseEnvType, clientIdLookup map[pkg.SourceType]string) (models.LighthouseSourceDefinition, error) {
	sourceDef, err := platform.GetSourceAllscripts(env, clientIdLookup)
	sourceDef.AuthorizationEndpoint = "https://stage-global.open.allscripts.com/fhirroute/fmhpatientauth/8dfaee91-c701-4e3b-8b8c-1dc50012e529/connect/authorize"
	sourceDef.TokenEndpoint = "https://stage-global.open.allscripts.com/fhirroute/fmhpatientauth/8dfaee91-c701-4e3b-8b8c-1dc50012e529/connect/token"

	sourceDef.Audience = "https://fhir01.northwell.edu/open"

	sourceDef.ApiEndpointBaseUrl = "https://fhir01.northwell.edu/open"
	// retrieve client-id, if available
	if clientId, clientIdOk := clientIdLookup[pkg.SourceTypeNorDev013]; clientIdOk {
		sourceDef.ClientId = clientId
	}
	sourceDef.RedirectUri = pkg.GetCallbackEndpoint(string(pkg.SourceTypeAllscripts))

	sourceDef.Display = "nor - DEV01"
	sourceDef.SourceType = pkg.SourceTypeNorDev013
	sourceDef.Category = []string{}
	sourceDef.Aliases = []string{}
	sourceDef.SecretKeyPrefix = "allscripts"

	return sourceDef, err
}
