// Copyright (C) Fasten Health, Inc. - All Rights Reserved.
//
// THIS FILE IS GENERATED BY https://github.com/fastenhealth/fasten-sources-gen
// PLEASE DO NOT EDIT BY HAND

package source

import (
	platform "github.com/fastenhealth/fasten-sources/definitions/internal/platform"
	models "github.com/fastenhealth/fasten-sources/definitions/models"
	pkg "github.com/fastenhealth/fasten-sources/pkg"
)

// https://fhir-myrecord.cerner.com/r4/47504f24-8f33-46ef-bd43-36455bc94e0b/metadata
func GetSourceNortonCountyHospital(env pkg.FastenLighthouseEnvType, clientIdLookup map[pkg.SourceType]string) (models.LighthouseSourceDefinition, error) {
	sourceDef, err := platform.GetSourceCerner(env, clientIdLookup)
	sourceDef.AuthorizationEndpoint = "https://authorization.cerner.com/tenants/47504f24-8f33-46ef-bd43-36455bc94e0b/protocols/oauth2/profiles/smart-v1/personas/patient/authorize"
	sourceDef.TokenEndpoint = "https://authorization.cerner.com/tenants/47504f24-8f33-46ef-bd43-36455bc94e0b/protocols/oauth2/profiles/smart-v1/token"
	sourceDef.IntrospectionEndpoint = "https://authorization.cerner.com/tokeninfo"

	sourceDef.Audience = "https://fhir-myrecord.cerner.com/r4/47504f24-8f33-46ef-bd43-36455bc94e0b"

	sourceDef.ApiEndpointBaseUrl = "https://fhir-myrecord.cerner.com/r4/47504f24-8f33-46ef-bd43-36455bc94e0b"
	// retrieve client-id, if available
	if clientId, clientIdOk := clientIdLookup[pkg.SourceTypeNortonCountyHospital]; clientIdOk {
		sourceDef.ClientId = clientId
	}
	sourceDef.RedirectUri = pkg.GetCallbackEndpoint(string(pkg.SourceTypeCerner))

	sourceDef.Display = "Norton County Hospital"
	sourceDef.SourceType = pkg.SourceTypeNortonCountyHospital
	sourceDef.Category = []string{"251E00000X", "261QM1300X", "261QP2300X", "261QR1300X", "282NC0060X", "314000000X"}
	sourceDef.Aliases = []string{"LOGAN CLINIC", "NORTON MEDICAL CLINIC"}
	sourceDef.Identifiers = map[string][]string{"http://hl7.org/fhir/sid/us-npi": []string{"1134125073", "1285659813", "1366043796", "1427088038", "1558380667", "1659724524", "1730519174", "1801892740"}}
	sourceDef.PatientAccessUrl = "https://www.ntcohosp.com"
	sourceDef.SecretKeyPrefix = "cerner"

	return sourceDef, err
}
