// Copyright (C) Fasten Health, Inc. - All Rights Reserved.
//
// THIS FILE IS GENERATED BY https://github.com/fastenhealth/fasten-sources-gen
// PLEASE DO NOT EDIT BY HAND

package source

import (
	platform "github.com/fastenhealth/fasten-sources/definitions/internal/platform"
	models "github.com/fastenhealth/fasten-sources/definitions/models"
	pkg "github.com/fastenhealth/fasten-sources/pkg"
)

// https://fhir-myrecord.cerner.com/r4/9bff9324-b2ff-4506-8825-324d6cd35169/metadata
func GetSourceOttawaCountyHealthCenter(env pkg.FastenLighthouseEnvType, clientIdLookup map[pkg.SourceType]string) (models.LighthouseSourceDefinition, error) {
	sourceDef, err := platform.GetSourceCerner(env, clientIdLookup)
	sourceDef.AuthorizationEndpoint = "https://authorization.cerner.com/tenants/9bff9324-b2ff-4506-8825-324d6cd35169/protocols/oauth2/profiles/smart-v1/personas/patient/authorize"
	sourceDef.TokenEndpoint = "https://authorization.cerner.com/tenants/9bff9324-b2ff-4506-8825-324d6cd35169/protocols/oauth2/profiles/smart-v1/token"
	sourceDef.IntrospectionEndpoint = "https://authorization.cerner.com/tokeninfo"

	sourceDef.Audience = "https://fhir-myrecord.cerner.com/r4/9bff9324-b2ff-4506-8825-324d6cd35169"

	sourceDef.ApiEndpointBaseUrl = "https://fhir-myrecord.cerner.com/r4/9bff9324-b2ff-4506-8825-324d6cd35169"
	// retrieve client-id, if available
	if clientId, clientIdOk := clientIdLookup[pkg.SourceTypeOttawaCountyHealthCenter]; clientIdOk {
		sourceDef.ClientId = clientId
	}
	sourceDef.RedirectUri = pkg.GetCallbackEndpoint(string(pkg.SourceTypeCerner))

	sourceDef.Display = "Ottawa County Health Center"
	sourceDef.SourceType = pkg.SourceTypeOttawaCountyHealthCenter
	sourceDef.Category = []string{"282NC0060X", "275N00000X"}
	sourceDef.Aliases = []string{"OTTAWA COUNTY HEALTH CENTER"}
	sourceDef.Identifiers = map[string][]string{"http://hl7.org/fhir/sid/us-npi": []string{"1760767339", "1689727208", "1902914823"}}
	sourceDef.BrandLogo = "ottawa-county-health-center.jpg"
	sourceDef.PatientAccessUrl = "https://www.facebook.com/Ottawa-County-Health-Center-111568958883951/"
	sourceDef.SecretKeyPrefix = "cerner"

	return sourceDef, err
}
