// Copyright (C) Fasten Health, Inc. - All Rights Reserved.
//
// THIS FILE IS GENERATED BY https://github.com/fastenhealth/fasten-sources-gen
// PLEASE DO NOT EDIT BY HAND

package source

import (
	platform "github.com/fastenhealth/fasten-sources/definitions/internal/platform"
	models "github.com/fastenhealth/fasten-sources/definitions/models"
	pkg "github.com/fastenhealth/fasten-sources/pkg"
)

// https://fhir-myrecord.cerner.com/r4/88f6f0ad-680b-460f-ba7c-9dd496dece04/metadata
func GetSourcePhillipsCountyHospital(env pkg.FastenLighthouseEnvType, clientIdLookup map[pkg.SourceType]string) (models.LighthouseSourceDefinition, error) {
	sourceDef, err := platform.GetSourceCerner(env, clientIdLookup)
	sourceDef.AuthorizationEndpoint = "https://authorization.cerner.com/tenants/88f6f0ad-680b-460f-ba7c-9dd496dece04/protocols/oauth2/profiles/smart-v1/personas/patient/authorize"
	sourceDef.TokenEndpoint = "https://authorization.cerner.com/tenants/88f6f0ad-680b-460f-ba7c-9dd496dece04/protocols/oauth2/profiles/smart-v1/token"
	sourceDef.IntrospectionEndpoint = "https://authorization.cerner.com/tokeninfo"

	sourceDef.Audience = "https://fhir-myrecord.cerner.com/r4/88f6f0ad-680b-460f-ba7c-9dd496dece04"

	sourceDef.ApiEndpointBaseUrl = "https://fhir-myrecord.cerner.com/r4/88f6f0ad-680b-460f-ba7c-9dd496dece04"
	// retrieve client-id, if available
	if clientId, clientIdOk := clientIdLookup[pkg.SourceTypePhillipsCountyHospital]; clientIdOk {
		sourceDef.ClientId = clientId
	}
	sourceDef.RedirectUri = pkg.GetCallbackEndpoint(string(pkg.SourceTypeCerner))

	sourceDef.Display = "Phillips County Hospital"
	sourceDef.SourceType = pkg.SourceTypePhillipsCountyHospital
	sourceDef.Category = []string{"208600000X", "282NC0060X", "363A00000X", "208D00000X", "363L00000X", "261QR1300X", "275N00000X", "207RP1001X", "213EP1101X", "367500000X", "261QE0700X"}
	sourceDef.Aliases = []string{"PHILLIPS COUNTY HEALTH SYSTEMS", "D/B/A PHILLIPS COUNTY MEDICAL CLINIC"}
	sourceDef.Identifiers = map[string][]string{"http://hl7.org/fhir/sid/us-npi": []string{"1659922292", "1548355761", "1366499717", "1689761892", "1639264492", "1457440067", "1639268246", "1447948302"}}
	sourceDef.PatientAccessUrl = "https://www.phillipshospital.org/"
	sourceDef.SecretKeyPrefix = "cerner"

	return sourceDef, err
}
