// Copyright (C) Fasten Health, Inc. - All Rights Reserved.
//
// THIS FILE IS GENERATED BY https://github.com/fastenhealth/fasten-sources-gen
// PLEASE DO NOT EDIT BY HAND

package source

import (
	platform "github.com/fastenhealth/fasten-sources/definitions/internal/platform"
	models "github.com/fastenhealth/fasten-sources/definitions/models"
	pkg "github.com/fastenhealth/fasten-sources/pkg"
)

// https://fhir.fhirpoint.open.allscripts.com/fhirroute/open/10017518/.well-known/smart-configuration
// https://fhir.fhirpoint.open.allscripts.com/fhirroute/open/10017518/metadata
func GetSourcePinnacleMedicalGroup(env pkg.FastenLighthouseEnvType, clientIdLookup map[pkg.SourceType]string) (models.LighthouseSourceDefinition, error) {
	sourceDef, err := platform.GetSourceAllscripts(env, clientIdLookup)
	sourceDef.AuthorizationEndpoint = "https://open.allscripts.com/fhirroute/fmhpatientauth/fmhorgid/217f4d27-431c-44ae-9292-a41900e86d63/connect/authorize"
	sourceDef.TokenEndpoint = "https://open.allscripts.com/fhirroute/fmhpatientauth/fmhorgid/217f4d27-431c-44ae-9292-a41900e86d63/connect/token"

	sourceDef.Audience = "https://fhir.fhirpoint.open.allscripts.com/fhirroute/open/10017518"

	sourceDef.ApiEndpointBaseUrl = "https://fhir.fhirpoint.open.allscripts.com/fhirroute/open/10017518"
	// retrieve client-id, if available
	if clientId, clientIdOk := clientIdLookup[pkg.SourceTypePinnacleMedicalGroup]; clientIdOk {
		sourceDef.ClientId = clientId
	}
	sourceDef.RedirectUri = pkg.GetCallbackEndpoint(string(pkg.SourceTypeAllscripts))

	sourceDef.Display = "Pinnacle Medical Group"
	sourceDef.SourceType = pkg.SourceTypePinnacleMedicalGroup
	sourceDef.Category = []string{"171W00000X", "207L00000X", "207Q00000X", "207QA0505X", "207R00000X", "207RG0100X", "208D00000X", "363LF0000X"}
	sourceDef.Aliases = []string{"PINNACLE MEDICAL GROUP"}
	sourceDef.Identifiers = map[string][]string{"http://hl7.org/fhir/sid/us-npi": []string{"1043404510", "1295968063", "1376121780", "1629371117", "1629515770"}}
	sourceDef.SecretKeyPrefix = "allscripts"

	return sourceDef, err
}
