// Copyright (C) Fasten Health, Inc. - All Rights Reserved.
//
// THIS FILE IS GENERATED BY https://github.com/fastenhealth/fasten-sources-gen
// PLEASE DO NOT EDIT BY HAND

package source

import (
	platform "github.com/fastenhealth/fasten-sources/definitions/internal/platform"
	models "github.com/fastenhealth/fasten-sources/definitions/models"
	pkg "github.com/fastenhealth/fasten-sources/pkg"
)

// https://fhir-myrecord.cerner.com/r4/82b5c78e-3511-4091-8bf4-9b7dbe078f0c/metadata
func GetSourcePrismaHealthMidlands1(env pkg.FastenLighthouseEnvType, clientIdLookup map[pkg.SourceType]string) (models.LighthouseSourceDefinition, error) {
	sourceDef, err := platform.GetSourceCerner(env, clientIdLookup)
	sourceDef.AuthorizationEndpoint = "https://authorization.cerner.com/tenants/82b5c78e-3511-4091-8bf4-9b7dbe078f0c/protocols/oauth2/profiles/smart-v1/personas/patient/authorize"
	sourceDef.TokenEndpoint = "https://authorization.cerner.com/tenants/82b5c78e-3511-4091-8bf4-9b7dbe078f0c/protocols/oauth2/profiles/smart-v1/token"
	sourceDef.IntrospectionEndpoint = "https://authorization.cerner.com/tokeninfo"

	sourceDef.Audience = "https://fhir-myrecord.cerner.com/r4/82b5c78e-3511-4091-8bf4-9b7dbe078f0c"

	sourceDef.ApiEndpointBaseUrl = "https://fhir-myrecord.cerner.com/r4/82b5c78e-3511-4091-8bf4-9b7dbe078f0c"
	// retrieve client-id, if available
	if clientId, clientIdOk := clientIdLookup[pkg.SourceTypePrismaHealthMidlands1]; clientIdOk {
		sourceDef.ClientId = clientId
	}
	sourceDef.RedirectUri = pkg.GetCallbackEndpoint(string(pkg.SourceTypeCerner))

	sourceDef.Display = "Prisma Health-Midlands"
	sourceDef.SourceType = pkg.SourceTypePrismaHealthMidlands1
	sourceDef.PatientAccessUrl = "https://www.dnb.com/business-directory/company-profiles.prisma_health-midlands.dd1f9bc0a480d8970803ddeb7c07c3e1.html"
	sourceDef.SecretKeyPrefix = "cerner"

	return sourceDef, err
}
