// Copyright (C) Fasten Health, Inc. - All Rights Reserved.
//
// THIS FILE IS GENERATED BY https://github.com/fastenhealth/fasten-sources-gen
// PLEASE DO NOT EDIT BY HAND

package source

import (
	platform "github.com/fastenhealth/fasten-sources/definitions/internal/platform"
	models "github.com/fastenhealth/fasten-sources/definitions/models"
	pkg "github.com/fastenhealth/fasten-sources/pkg"
)

// https://fhir.nextgen.com/nge/prod/fhir-api-r4/fhir/r4/metadata
func GetSourceProlianceOrthopedicAssociates(env pkg.FastenLighthouseEnvType, clientIdLookup map[pkg.SourceType]string) (models.LighthouseSourceDefinition, error) {
	sourceDef, err := platform.GetSourceNextgen(env, clientIdLookup)
	sourceDef.AuthorizationEndpoint = "https://fhir.nextgen.com/nge/prod/patient-oauth/authorize"
	sourceDef.TokenEndpoint = "https://fhir.nextgen.com/nge/prod/patient-oauth/token"

	sourceDef.Audience = "https://fhir.nextgen.com/nge/prod/fhir-api-r4/fhir/r4"

	sourceDef.ApiEndpointBaseUrl = "https://fhir.nextgen.com/nge/prod/fhir-api-r4/fhir/r4"
	// retrieve client-id, if available
	if clientId, clientIdOk := clientIdLookup[pkg.SourceTypeProlianceOrthopedicAssociates]; clientIdOk {
		sourceDef.ClientId = clientId
	}
	sourceDef.RedirectUri = pkg.GetCallbackEndpoint(string(pkg.SourceTypeNextgen))

	sourceDef.Display = "Proliance Orthopedic Associates"
	sourceDef.SourceType = pkg.SourceTypeProlianceOrthopedicAssociates
	sourceDef.Category = []string{"207QS0010X", "207X00000X", "207XS0106X", "207XS0114X", "207XS0117X", "207XX0004X", "207XX0005X", "207XX0801X", "2081P2900X", "2083X0100X", "261QM1200X", "261QM1300X", "332B00000X", "363AS0400X", "363L00000X", "363LF0000X", "363LG0600X"}
	sourceDef.Aliases = []string{"PROLIANCE ORTHOPEDIC ASSOCIATES", "PROLIANCE ORTHOPEDIC ASSOCIATES MRI"}
	sourceDef.Identifiers = map[string][]string{"http://hl7.org/fhir/sid/us-npi": []string{"1417512021", "1417990797", "1932262904", "1962894626"}}
	sourceDef.BrandLogo = "proliance-orthopedic-associates.jpg"
	sourceDef.PatientAccessUrl = "https://hi-in.facebook.com/POARenton/"
	sourceDef.SecretKeyPrefix = "nextgen"

	return sourceDef, err
}
