// Copyright (C) Fasten Health, Inc. - All Rights Reserved.
//
// THIS FILE IS GENERATED BY https://github.com/fastenhealth/fasten-sources-gen
// PLEASE DO NOT EDIT BY HAND

package source

import (
	platform "github.com/fastenhealth/fasten-sources/definitions/internal/platform"
	models "github.com/fastenhealth/fasten-sources/definitions/models"
	pkg "github.com/fastenhealth/fasten-sources/pkg"
)

// https://scmprodweb.pv0.hos.allscriptscloud.com/R2/fhir/metadata
func GetSourcePv04(env pkg.FastenLighthouseEnvType, clientIdLookup map[pkg.SourceType]string) (models.LighthouseSourceDefinition, error) {
	sourceDef, err := platform.GetSourceAllscripts(env, clientIdLookup)
	sourceDef.AuthorizationEndpoint = "https://scmprodweb.pv0.hos.allscriptscloud.com/authorization/connect/authorize"
	sourceDef.TokenEndpoint = "https://scmprodweb.pv0.hos.allscriptscloud.com/authorization/connect/token"

	sourceDef.Audience = "https://scmprodweb.pv0.hos.allscriptscloud.com/R2/fhir"

	sourceDef.ApiEndpointBaseUrl = "https://scmprodweb.pv0.hos.allscriptscloud.com/R2/fhir"
	// retrieve client-id, if available
	if clientId, clientIdOk := clientIdLookup[pkg.SourceTypePv04]; clientIdOk {
		sourceDef.ClientId = clientId
	}
	sourceDef.RedirectUri = pkg.GetCallbackEndpoint(string(pkg.SourceTypeAllscripts))

	sourceDef.Display = "PV0"
	sourceDef.SourceType = pkg.SourceTypePv04
	sourceDef.Hidden = true
	sourceDef.SecretKeyPrefix = "allscripts"

	return sourceDef, err
}
