// Copyright (C) Fasten Health, Inc. - All Rights Reserved.
//
// THIS FILE IS GENERATED BY https://github.com/fastenhealth/fasten-sources-gen
// PLEASE DO NOT EDIT BY HAND

package source

import (
	platform "github.com/fastenhealth/fasten-sources/definitions/internal/platform"
	models "github.com/fastenhealth/fasten-sources/definitions/models"
	pkg "github.com/fastenhealth/fasten-sources/pkg"
)

// https://fhir-myrecord.cerner.com/r4/1d6c3167-ceed-47b0-b6f7-156a9cb2ffbe/metadata
func GetSourceRasoAndCohenGastroenterology(env pkg.FastenLighthouseEnvType, clientIdLookup map[pkg.SourceType]string) (models.LighthouseSourceDefinition, error) {
	sourceDef, err := platform.GetSourceCerner(env, clientIdLookup)
	sourceDef.AuthorizationEndpoint = "https://authorization.cerner.com/tenants/1d6c3167-ceed-47b0-b6f7-156a9cb2ffbe/protocols/oauth2/profiles/smart-v1/personas/patient/authorize"
	sourceDef.TokenEndpoint = "https://authorization.cerner.com/tenants/1d6c3167-ceed-47b0-b6f7-156a9cb2ffbe/protocols/oauth2/profiles/smart-v1/token"
	sourceDef.IntrospectionEndpoint = "https://authorization.cerner.com/tokeninfo"

	sourceDef.Audience = "https://fhir-myrecord.cerner.com/r4/1d6c3167-ceed-47b0-b6f7-156a9cb2ffbe"

	sourceDef.ApiEndpointBaseUrl = "https://fhir-myrecord.cerner.com/r4/1d6c3167-ceed-47b0-b6f7-156a9cb2ffbe"
	// retrieve client-id, if available
	if clientId, clientIdOk := clientIdLookup[pkg.SourceTypeRasoAndCohenGastroenterology]; clientIdOk {
		sourceDef.ClientId = clientId
	}
	sourceDef.RedirectUri = pkg.GetCallbackEndpoint(string(pkg.SourceTypeCerner))

	sourceDef.Display = "Raso and Cohen Gastroenterology"
	sourceDef.SourceType = pkg.SourceTypeRasoAndCohenGastroenterology
	sourceDef.PatientAccessUrl = "https://rasocohengastroenterology.com/"
	sourceDef.SecretKeyPrefix = "cerner"

	return sourceDef, err
}
