// Copyright (C) Fasten Health, Inc. - All Rights Reserved.
//
// THIS FILE IS GENERATED BY https://github.com/fastenhealth/fasten-sources-gen
// PLEASE DO NOT EDIT BY HAND

package source

import (
	platform "github.com/fastenhealth/fasten-sources/definitions/internal/platform"
	models "github.com/fastenhealth/fasten-sources/definitions/models"
	pkg "github.com/fastenhealth/fasten-sources/pkg"
)

// https://fhir-myrecord.cerner.com/r4/ba83b482-215a-4958-9629-47fddfaae0e6/metadata
func GetSourceRehabilitationHospitalOfThePacific(env pkg.FastenLighthouseEnvType, clientIdLookup map[pkg.SourceType]string) (models.LighthouseSourceDefinition, error) {
	sourceDef, err := platform.GetSourceCerner(env, clientIdLookup)
	sourceDef.AuthorizationEndpoint = "https://authorization.cerner.com/tenants/ba83b482-215a-4958-9629-47fddfaae0e6/protocols/oauth2/profiles/smart-v1/personas/patient/authorize"
	sourceDef.TokenEndpoint = "https://authorization.cerner.com/tenants/ba83b482-215a-4958-9629-47fddfaae0e6/protocols/oauth2/profiles/smart-v1/token"
	sourceDef.IntrospectionEndpoint = "https://authorization.cerner.com/tokeninfo"

	sourceDef.Audience = "https://fhir-myrecord.cerner.com/r4/ba83b482-215a-4958-9629-47fddfaae0e6"

	sourceDef.ApiEndpointBaseUrl = "https://fhir-myrecord.cerner.com/r4/ba83b482-215a-4958-9629-47fddfaae0e6"
	// retrieve client-id, if available
	if clientId, clientIdOk := clientIdLookup[pkg.SourceTypeRehabilitationHospitalOfThePacific]; clientIdOk {
		sourceDef.ClientId = clientId
	}
	sourceDef.RedirectUri = pkg.GetCallbackEndpoint(string(pkg.SourceTypeCerner))

	sourceDef.Display = "Rehabilitation Hospital of the Pacific"
	sourceDef.SourceType = pkg.SourceTypeRehabilitationHospitalOfThePacific
	sourceDef.Category = []string{"261QM1300X", "261QM2500X", "261QP2300X", "261QP3300X", "261QR0200X", "261QR0400X", "283X00000X", "314000000X", "332B00000X", "3336I0012X"}
	sourceDef.Aliases = []string{"REHAB AT HILO", "REHABILITATION HOSPITAL OF THE PACIFIC PHYSICIANS CLINIC"}
	sourceDef.Identifiers = map[string][]string{"http://hl7.org/fhir/sid/us-npi": []string{"1023127750", "1073537510", "1073617635", "1114036894", "1174632897", "1487758199", "1598785388", "1730580424"}}
	sourceDef.BrandLogo = "rehabilitation-hospital-of-the-pacific.svg"
	sourceDef.PatientAccessUrl = "https://www.rehabhospital.org/"
	sourceDef.SecretKeyPrefix = "cerner"

	return sourceDef, err
}
