// Copyright (C) Fasten Health, Inc. - All Rights Reserved.
//
// THIS FILE IS GENERATED BY https://github.com/fastenhealth/fasten-sources-gen
// PLEASE DO NOT EDIT BY HAND

package source

import (
	platform "github.com/fastenhealth/fasten-sources/definitions/internal/platform"
	models "github.com/fastenhealth/fasten-sources/definitions/models"
	pkg "github.com/fastenhealth/fasten-sources/pkg"
)

// https://fhir4.healow.com/fhir/r4/JJHCAD/metadata
func GetSourceScenicBluffsCommunityHealthCenters(env pkg.FastenLighthouseEnvType, clientIdLookup map[pkg.SourceType]string) (models.LighthouseSourceDefinition, error) {
	sourceDef, err := platform.GetSourceEclinicalworks(env, clientIdLookup)
	sourceDef.AuthorizationEndpoint = "https://oauthserver.eclinicalworks.com/oauth/oauth2/authorize"
	sourceDef.TokenEndpoint = "https://oauthserver.eclinicalworks.com/oauth/oauth2/token"

	sourceDef.Audience = "https://fhir4.healow.com/fhir/r4/JJHCAD"

	sourceDef.ApiEndpointBaseUrl = "https://fhir4.healow.com/fhir/r4/JJHCAD"
	// retrieve client-id, if available
	if clientId, clientIdOk := clientIdLookup[pkg.SourceTypeScenicBluffsCommunityHealthCenters]; clientIdOk {
		sourceDef.ClientId = clientId
	}
	sourceDef.RedirectUri = pkg.GetCallbackEndpoint(string(pkg.SourceTypeEclinicalworks))

	sourceDef.Display = "Scenic Bluffs Community Health Centers"
	sourceDef.SourceType = pkg.SourceTypeScenicBluffsCommunityHealthCenters
	sourceDef.Category = []string{"261QD0000X", "261QF0400X", "261QM0801X"}
	sourceDef.Aliases = []string{"SCENIC BLUFFS COMMUNITY HEALTH CENTERS"}
	sourceDef.Identifiers = map[string][]string{"http://hl7.org/fhir/sid/us-npi": []string{"1073975306", "1104890078", "1134773864", "1134773872", "1154783629", "1326693847", "1649824376", "1689036865", "1821642562"}}
	sourceDef.SecretKeyPrefix = "eclinicalworks"

	return sourceDef, err
}
