// Copyright (C) Fasten Health, Inc. - All Rights Reserved.
//
// THIS FILE IS GENERATED BY https://github.com/fastenhealth/fasten-sources-gen
// PLEASE DO NOT EDIT BY HAND

package source

import (
	platform "github.com/fastenhealth/fasten-sources/definitions/internal/platform"
	models "github.com/fastenhealth/fasten-sources/definitions/models"
	pkg "github.com/fastenhealth/fasten-sources/pkg"
)

// https://fhir-myrecord.cerner.com/r4/0f01f77a-8c85-47f1-aaa5-2b7968c0806e/.well-known/smart-configuration
// https://fhir-myrecord.cerner.com/r4/0f01f77a-8c85-47f1-aaa5-2b7968c0806e/metadata
func GetSourceSeiffCenterForAestheticAndReconstructiveSurgery(env pkg.FastenLighthouseEnvType) (models.LighthouseSourceDefinition, error) {
	sourceDef, err := platform.GetSourceCerner(env)
	sourceDef.AuthorizationEndpoint = "https://authorization.cerner.com/tenants/0f01f77a-8c85-47f1-aaa5-2b7968c0806e/protocols/oauth2/profiles/smart-v1/personas/patient/authorize"
	sourceDef.TokenEndpoint = "https://authorization.cerner.com/tenants/0f01f77a-8c85-47f1-aaa5-2b7968c0806e/protocols/oauth2/profiles/smart-v1/token"
	sourceDef.IntrospectionEndpoint = "https://authorization.cerner.com/tokeninfo"

	sourceDef.Audience = "https://fhir-myrecord.cerner.com/r4/0f01f77a-8c85-47f1-aaa5-2b7968c0806e"

	sourceDef.ApiEndpointBaseUrl = "https://fhir-myrecord.cerner.com/r4/0f01f77a-8c85-47f1-aaa5-2b7968c0806e"
	sourceDef.RedirectUri = pkg.GetCallbackEndpoint(string(pkg.SourceTypeCerner))

	sourceDef.Display = "Seiff Center for Aesthetic and Reconstructive Surgery"
	sourceDef.SourceType = pkg.SourceTypeSeiffCenterForAestheticAndReconstructiveSurgery
	sourceDef.Hidden = true
	sourceDef.SecretKeyPrefix = "cerner"

	return sourceDef, err
}
