// Copyright (C) Fasten Health, Inc. - All Rights Reserved.
//
// THIS FILE IS GENERATED BY https://github.com/fastenhealth/fasten-sources-gen
// PLEASE DO NOT EDIT BY HAND

package source

import (
	platform "github.com/fastenhealth/fasten-sources/definitions/internal/platform"
	models "github.com/fastenhealth/fasten-sources/definitions/models"
	pkg "github.com/fastenhealth/fasten-sources/pkg"
)

// https://epicproxy.et1024.epichosted.com/FHIRProxy/api/FHIR/R4/metadata
func GetSourceSouthGeorgiaMedicalCenter(env pkg.FastenLighthouseEnvType, clientIdLookup map[pkg.SourceType]string) (models.LighthouseSourceDefinition, error) {
	sourceDef, err := platform.GetSourceEpic(env, clientIdLookup)
	sourceDef.AuthorizationEndpoint = "https://epicproxy.et1024.epichosted.com/FHIRProxy/oauth2/authorize"
	sourceDef.TokenEndpoint = "https://epicproxy.et1024.epichosted.com/FHIRProxy/oauth2/token"
	sourceDef.RegistrationEndpoint = "https://epicproxy.et1024.epichosted.com/FHIRProxy/oauth2/register"

	sourceDef.Audience = "https://epicproxy.et1024.epichosted.com/FHIRProxy/api/FHIR/R4"

	sourceDef.ApiEndpointBaseUrl = "https://epicproxy.et1024.epichosted.com/FHIRProxy/api/FHIR/R4"
	// retrieve client-id, if available
	if clientId, clientIdOk := clientIdLookup[pkg.SourceTypeSouthGeorgiaMedicalCenter]; clientIdOk {
		sourceDef.ClientId = clientId
	}
	sourceDef.RedirectUri = pkg.GetCallbackEndpoint(string(pkg.SourceTypeEpic))

	sourceDef.Display = "South Georgia Medical Center"
	sourceDef.SourceType = pkg.SourceTypeSouthGeorgiaMedicalCenter
	sourceDef.Category = []string{"282N00000X", "261QM0850X", "261QM0855X", "261QU0200X", "341600000X", "261QR0400X", "273Y00000X", "333600000X"}
	sourceDef.Aliases = []string{"SOUTH GEORGIA MEDICAL CENTER"}
	sourceDef.Identifiers = map[string][]string{"http://hl7.org/fhir/sid/us-npi": []string{"1891045191", "1306896253", "1467404046", "1649641721", "1386626570", "1831171867"}}
	sourceDef.SecretKeyPrefix = "epic"

	return sourceDef, err
}
