// Copyright (C) Fasten Health, Inc. - All Rights Reserved.
//
// THIS FILE IS GENERATED BY https://github.com/fastenhealth/fasten-sources-gen
// PLEASE DO NOT EDIT BY HAND

package source

import (
	platform "github.com/fastenhealth/fasten-sources/definitions/internal/platform"
	models "github.com/fastenhealth/fasten-sources/definitions/models"
	pkg "github.com/fastenhealth/fasten-sources/pkg"
)

// https://fhir-myrecord.cerner.com/r4/71a7ae5c-fd06-4e97-9d52-1b2ec662d620/metadata
func GetSourceStVincentsHospital(env pkg.FastenLighthouseEnvType, clientIdLookup map[pkg.SourceType]string) (models.LighthouseSourceDefinition, error) {
	sourceDef, err := platform.GetSourceCerner(env, clientIdLookup)
	sourceDef.AuthorizationEndpoint = "https://authorization.cerner.com/tenants/71a7ae5c-fd06-4e97-9d52-1b2ec662d620/protocols/oauth2/profiles/smart-v1/personas/patient/authorize"
	sourceDef.TokenEndpoint = "https://authorization.cerner.com/tenants/71a7ae5c-fd06-4e97-9d52-1b2ec662d620/protocols/oauth2/profiles/smart-v1/token"
	sourceDef.IntrospectionEndpoint = "https://authorization.cerner.com/tokeninfo"

	sourceDef.Audience = "https://fhir-myrecord.cerner.com/r4/71a7ae5c-fd06-4e97-9d52-1b2ec662d620"

	sourceDef.ApiEndpointBaseUrl = "https://fhir-myrecord.cerner.com/r4/71a7ae5c-fd06-4e97-9d52-1b2ec662d620"
	// retrieve client-id, if available
	if clientId, clientIdOk := clientIdLookup[pkg.SourceTypeStVincentsHospital]; clientIdOk {
		sourceDef.ClientId = clientId
	}
	sourceDef.RedirectUri = pkg.GetCallbackEndpoint(string(pkg.SourceTypeCerner))

	sourceDef.Display = "St. Vincent's Hospital"
	sourceDef.SourceType = pkg.SourceTypeStVincentsHospital
	sourceDef.Category = []string{"2084P0800X", "363AS0400X", "335V00000X", "333600000X"}
	sourceDef.Identifiers = map[string][]string{"http://hl7.org/fhir/sid/us-npi": []string{"1518107119", "1134255409", "1245375963"}}
	sourceDef.BrandLogo = "st-vincents-hospital.svg"
	sourceDef.PatientAccessUrl = "https://saint-vincent.childrensmiraclenetworkhospitals.org/?gclid=Cj0KCQiA6rCgBhDVARIsAK1kGPIf-KV5iByToG-IFAzZYZBEMyyxP4GGNn8atvmA9Qo_2Wx7pJs4VzsaAlDNEALw_wcB"
	sourceDef.SecretKeyPrefix = "cerner"

	return sourceDef, err
}
