// Copyright (C) Fasten Health, Inc. - All Rights Reserved.
//
// THIS FILE IS GENERATED BY https://github.com/fastenhealth/fasten-sources-gen
// PLEASE DO NOT EDIT BY HAND

package source

import (
	platform "github.com/fastenhealth/fasten-sources/definitions/internal/platform"
	models "github.com/fastenhealth/fasten-sources/definitions/models"
	pkg "github.com/fastenhealth/fasten-sources/pkg"
)

// https://fhir-myrecord.cerner.com/r4/6045c542-91fb-42f0-88cd-540b035e6ca7/metadata
func GetSourceTheResourceCenter(env pkg.FastenLighthouseEnvType, clientIdLookup map[pkg.SourceType]string) (models.LighthouseSourceDefinition, error) {
	sourceDef, err := platform.GetSourceCerner(env, clientIdLookup)
	sourceDef.AuthorizationEndpoint = "https://authorization.cerner.com/tenants/6045c542-91fb-42f0-88cd-540b035e6ca7/protocols/oauth2/profiles/smart-v1/personas/patient/authorize"
	sourceDef.TokenEndpoint = "https://authorization.cerner.com/tenants/6045c542-91fb-42f0-88cd-540b035e6ca7/protocols/oauth2/profiles/smart-v1/token"
	sourceDef.IntrospectionEndpoint = "https://authorization.cerner.com/tokeninfo"

	sourceDef.Audience = "https://fhir-myrecord.cerner.com/r4/6045c542-91fb-42f0-88cd-540b035e6ca7"

	sourceDef.ApiEndpointBaseUrl = "https://fhir-myrecord.cerner.com/r4/6045c542-91fb-42f0-88cd-540b035e6ca7"
	// retrieve client-id, if available
	if clientId, clientIdOk := clientIdLookup[pkg.SourceTypeTheResourceCenter]; clientIdOk {
		sourceDef.ClientId = clientId
	}
	sourceDef.RedirectUri = pkg.GetCallbackEndpoint(string(pkg.SourceTypeCerner))

	sourceDef.Display = "The Resource Center"
	sourceDef.SourceType = pkg.SourceTypeTheResourceCenter
	sourceDef.Category = []string{"225B00000X", "251C00000X", "261QC1500X", "261QD0000X", "261QM0801X", "261QR0401X"}
	sourceDef.Identifiers = map[string][]string{"http://hl7.org/fhir/sid/us-npi": []string{"1003979345", "1013079326", "1295924280", "1396808911", "1598931453", "1598931560", "1659434835", "1700940384", "1912060252", "1982766051"}}
	sourceDef.SecretKeyPrefix = "cerner"

	return sourceDef, err
}
