// Copyright (C) Fasten Health, Inc. - All Rights Reserved.
//
// THIS FILE IS GENERATED BY https://github.com/fastenhealth/fasten-sources-gen
// PLEASE DO NOT EDIT BY HAND

package source

import (
	platform "github.com/fastenhealth/fasten-sources/definitions/internal/platform"
	models "github.com/fastenhealth/fasten-sources/definitions/models"
	pkg "github.com/fastenhealth/fasten-sources/pkg"
)

// https://epicfhir.unitypoint.org/ProdFHIR/api/FHIR/R4/.well-known/smart-configuration
// https://epicfhir.unitypoint.org/ProdFHIR/api/FHIR/R4/metadata
func GetSourceUnitypointHealth(env pkg.FastenLighthouseEnvType) (models.LighthouseSourceDefinition, error) {
	sourceDef, err := platform.GetSourceEpic(env)
	sourceDef.AuthorizationEndpoint = "https://epicfhir.unitypoint.org/ProdFHIR/oauth2/authorize"
	sourceDef.TokenEndpoint = "https://epicfhir.unitypoint.org/ProdFHIR/oauth2/token"

	sourceDef.Audience = "https://epicfhir.unitypoint.org/ProdFHIR/api/FHIR/R4"

	sourceDef.ApiEndpointBaseUrl = "https://epicfhir.unitypoint.org/ProdFHIR/api/FHIR/R4"
	if env == pkg.FastenLighthouseEnvSandbox {
		sourceDef.ClientId = ""
	}
	sourceDef.RedirectUri = pkg.GetCallbackEndpoint(string(pkg.SourceTypeEpic))

	sourceDef.Display = "UnityPoint Health"
	sourceDef.SourceType = pkg.SourceTypeUnitypointHealth
	sourceDef.Enabled = true
	sourceDef.SecretKeyPrefix = "epic"

	return sourceDef, err
}
