// Copyright (C) Fasten Health, Inc. - All Rights Reserved.
//
// THIS FILE IS GENERATED BY https://github.com/fastenhealth/fasten-sources-gen
// PLEASE DO NOT EDIT BY HAND

package source

import (
	platform "github.com/fastenhealth/fasten-sources/definitions/internal/platform"
	models "github.com/fastenhealth/fasten-sources/definitions/models"
	pkg "github.com/fastenhealth/fasten-sources/pkg"
)

// https://EpicIntprxyPRD.swmed.edu/FHIR/api/FHIR/R4/metadata
func GetSourceUniversityOfTexasSouthwesternMedicalCenter(env pkg.FastenLighthouseEnvType, clientIdLookup map[pkg.SourceType]string) (models.LighthouseSourceDefinition, error) {
	sourceDef, err := platform.GetSourceEpic(env, clientIdLookup)
	sourceDef.AuthorizationEndpoint = "https://EpicIntprxyPRD.swmed.edu/FHIR/oauth2/authorize"
	sourceDef.TokenEndpoint = "https://EpicIntprxyPRD.swmed.edu/FHIR/oauth2/token"

	sourceDef.Audience = "https://EpicIntprxyPRD.swmed.edu/FHIR/api/FHIR/R4"

	sourceDef.ApiEndpointBaseUrl = "https://EpicIntprxyPRD.swmed.edu/FHIR/api/FHIR/R4"
	// retrieve client-id, if available
	if clientId, clientIdOk := clientIdLookup[pkg.SourceTypeUniversityOfTexasSouthwesternMedicalCenter]; clientIdOk {
		sourceDef.ClientId = clientId
	}
	sourceDef.RedirectUri = pkg.GetCallbackEndpoint(string(pkg.SourceTypeEpic))

	sourceDef.Display = "University of Texas Southwestern Medical Center"
	sourceDef.SourceType = pkg.SourceTypeUniversityOfTexasSouthwesternMedicalCenter
	sourceDef.Category = []string{"286500000X", "367500000X"}
	sourceDef.Identifiers = map[string][]string{"http://hl7.org/fhir/sid/us-npi": []string{"1164591822", "1992032619"}}
	sourceDef.SecretKeyPrefix = "epic"

	return sourceDef, err
}
