// Copyright (C) Fasten Health, Inc. - All Rights Reserved.
//
// THIS FILE IS GENERATED BY https://github.com/fastenhealth/fasten-sources-gen
// PLEASE DO NOT EDIT BY HAND

package source

import (
	platform "github.com/fastenhealth/fasten-sources/definitions/internal/platform"
	models "github.com/fastenhealth/fasten-sources/definitions/models"
	pkg "github.com/fastenhealth/fasten-sources/pkg"
)

// https://epic-arr.utmb.edu/fhir-prd/api/FHIR/R4/metadata
func GetSourceUniversityOfTexasMedicalBranch(env pkg.FastenLighthouseEnvType, clientIdLookup map[pkg.SourceType]string) (models.LighthouseSourceDefinition, error) {
	sourceDef, err := platform.GetSourceEpic(env, clientIdLookup)
	sourceDef.AuthorizationEndpoint = "https://epic-arr.utmb.edu/fhir-prd/oauth2/authorize"
	sourceDef.TokenEndpoint = "https://epic-arr.utmb.edu/fhir-prd/oauth2/token"

	sourceDef.Audience = "https://epic-arr.utmb.edu/fhir-prd/api/FHIR/R4"

	sourceDef.ApiEndpointBaseUrl = "https://epic-arr.utmb.edu/fhir-prd/api/FHIR/R4"
	// retrieve client-id, if available
	if clientId, clientIdOk := clientIdLookup[pkg.SourceTypeUniversityOfTexasMedicalBranch]; clientIdOk {
		sourceDef.ClientId = clientId
	}
	sourceDef.RedirectUri = pkg.GetCallbackEndpoint(string(pkg.SourceTypeEpic))

	sourceDef.Display = "University of Texas Medical Branch"
	sourceDef.SourceType = pkg.SourceTypeUniversityOfTexasMedicalBranch
	sourceDef.Category = []string{"3336C0002X", "302R00000X", "261QP0905X", "282N00000X", "261QD1600X", "261QM1300X", "207Q00000X", "282NW0100X", "261QA1903X", "261QC0050X", "281P00000X", "341600000X"}
	sourceDef.Aliases = []string{"UNIVERSITY OF TEXAS MEDICAL BRANCH"}
	sourceDef.Identifiers = map[string][]string{"http://hl7.org/fhir/sid/us-npi": []string{"1306802384", "1912207911", "1033310388", "1710292800", "1629283569", "1295119493", "1407524135", "1962871699", "1457802472", "1548226988"}}
	sourceDef.SecretKeyPrefix = "epic"

	return sourceDef, err
}
