// Copyright (C) Fasten Health, Inc. - All Rights Reserved.
//
// THIS FILE IS GENERATED BY https://github.com/fastenhealth/fasten-sources-gen
// PLEASE DO NOT EDIT BY HAND

package source

import (
	platform "github.com/fastenhealth/fasten-sources/definitions/internal/platform"
	models "github.com/fastenhealth/fasten-sources/definitions/models"
	pkg "github.com/fastenhealth/fasten-sources/pkg"
)

// https://ucsoap.uams.edu/FHIRProxy/api/FHIR/R4/metadata
func GetSourceUniversityOfArkansasForMedicalSciences(env pkg.FastenLighthouseEnvType, clientIdLookup map[pkg.SourceType]string) (models.LighthouseSourceDefinition, error) {
	sourceDef, err := platform.GetSourceEpic(env, clientIdLookup)
	sourceDef.AuthorizationEndpoint = "https://ucsoap.uams.edu/FHIRProxy/oauth2/authorize"
	sourceDef.TokenEndpoint = "https://ucsoap.uams.edu/FHIRProxy/oauth2/token"

	sourceDef.Audience = "https://ucsoap.uams.edu/FHIRProxy/api/FHIR/R4"

	sourceDef.ApiEndpointBaseUrl = "https://ucsoap.uams.edu/FHIRProxy/api/FHIR/R4"
	// retrieve client-id, if available
	if clientId, clientIdOk := clientIdLookup[pkg.SourceTypeUniversityOfArkansasForMedicalSciences]; clientIdOk {
		sourceDef.ClientId = clientId
	}
	sourceDef.RedirectUri = pkg.GetCallbackEndpoint(string(pkg.SourceTypeEpic))

	sourceDef.Display = "University of Arkansas for Medical Sciences"
	sourceDef.SourceType = pkg.SourceTypeUniversityOfArkansasForMedicalSciences
	sourceDef.Category = []string{"3336S0011X", "207L00000X", "207P00000X", "207W00000X", "207XP3100X", "207YP0228X", "2080N0001X", "2080P0202X", "2080P0203X", "2080P0207X", "2084P0804X", "2085R0202X", "2086S0120X", "2088P0231X", "208000000X", "2080P0006X", "207R00000X", "332B00000X", "363L00000X", "104100000X", "133V00000X", "273R00000X"}
	sourceDef.Aliases = []string{"CHILD STUDY CENTER", "CHILDREN'S UNIVERSITY MEDICAL GROUP", "CHILDRENS UNIVERSITY MEDICAL GROUP", "KIDS FIRST SEARCY", "MCPG DME JEI OPTICAL SHOP", "NURSE PRACTITIONER SERVICES", "UAMS INTERNAL MEDICINE GROUP PCP"}
	sourceDef.Identifiers = map[string][]string{"http://hl7.org/fhir/sid/us-npi": []string{"1477998847", "1346230968", "1467528026", "1750457842", "1669534749", "1043373590", "1629130802", "1750533642", "1679725543", "1215167937"}}
	sourceDef.PatientAccessUrl = "https://uamshealth.com/"
	sourceDef.SecretKeyPrefix = "epic"

	return sourceDef, err
}
