// Copyright (C) Fasten Health, Inc. - All Rights Reserved.
//
// THIS FILE IS GENERATED BY https://github.com/fastenhealth/fasten-sources-gen
// PLEASE DO NOT EDIT BY HAND

package source

import (
	platform "github.com/fastenhealth/fasten-sources/definitions/internal/platform"
	models "github.com/fastenhealth/fasten-sources/definitions/models"
	pkg "github.com/fastenhealth/fasten-sources/pkg"
)

// https://fhir-myrecord.cerner.com/r4/98617d0b-48d0-431b-8ad4-46d64800d954/metadata
func GetSourceUwharriePodiatryLlc(env pkg.FastenLighthouseEnvType, clientIdLookup map[pkg.SourceType]string) (models.LighthouseSourceDefinition, error) {
	sourceDef, err := platform.GetSourceCerner(env, clientIdLookup)
	sourceDef.AuthorizationEndpoint = "https://authorization.cerner.com/tenants/98617d0b-48d0-431b-8ad4-46d64800d954/protocols/oauth2/profiles/smart-v1/personas/patient/authorize"
	sourceDef.TokenEndpoint = "https://authorization.cerner.com/tenants/98617d0b-48d0-431b-8ad4-46d64800d954/protocols/oauth2/profiles/smart-v1/token"
	sourceDef.IntrospectionEndpoint = "https://authorization.cerner.com/tokeninfo"

	sourceDef.Audience = "https://fhir-myrecord.cerner.com/r4/98617d0b-48d0-431b-8ad4-46d64800d954"

	sourceDef.ApiEndpointBaseUrl = "https://fhir-myrecord.cerner.com/r4/98617d0b-48d0-431b-8ad4-46d64800d954"
	// retrieve client-id, if available
	if clientId, clientIdOk := clientIdLookup[pkg.SourceTypeUwharriePodiatryLlc]; clientIdOk {
		sourceDef.ClientId = clientId
	}
	sourceDef.RedirectUri = pkg.GetCallbackEndpoint(string(pkg.SourceTypeCerner))

	sourceDef.Display = "Uwharrie Podiatry LLC"
	sourceDef.SourceType = pkg.SourceTypeUwharriePodiatryLlc
	sourceDef.Category = []string{}
	sourceDef.Aliases = []string{}
	sourceDef.PatientAccessUrl = "https://www.facebook.com/people/Uwharrie-Podiatry-LLC/100067209215040/"
	sourceDef.SecretKeyPrefix = "cerner"

	return sourceDef, err
}
