// Copyright (C) Fasten Health, Inc. - All Rights Reserved.
//
// THIS FILE IS GENERATED BY https://github.com/fastenhealth/fasten-sources-gen
// PLEASE DO NOT EDIT BY HAND

package source

import (
	platform "github.com/fastenhealth/fasten-sources/definitions/internal/platform"
	models "github.com/fastenhealth/fasten-sources/definitions/models"
	pkg "github.com/fastenhealth/fasten-sources/pkg"
)

// https://FHIR.valleymed.org/FHIR-PRD/api/FHIR/R4/metadata
func GetSourceValleyMedicalCenter(env pkg.FastenLighthouseEnvType, clientIdLookup map[pkg.SourceType]string) (models.LighthouseSourceDefinition, error) {
	sourceDef, err := platform.GetSourceEpic(env, clientIdLookup)
	sourceDef.AuthorizationEndpoint = "https://FHIR.valleymed.org/FHIR-PRD/oauth2/authorize"
	sourceDef.TokenEndpoint = "https://FHIR.valleymed.org/FHIR-PRD/oauth2/token"

	sourceDef.Audience = "https://FHIR.valleymed.org/FHIR-PRD/api/FHIR/R4"

	sourceDef.ApiEndpointBaseUrl = "https://FHIR.valleymed.org/FHIR-PRD/api/FHIR/R4"
	// retrieve client-id, if available
	if clientId, clientIdOk := clientIdLookup[pkg.SourceTypeValleyMedicalCenter]; clientIdOk {
		sourceDef.ClientId = clientId
	}
	sourceDef.RedirectUri = pkg.GetCallbackEndpoint(string(pkg.SourceTypeEpic))

	sourceDef.Display = "Valley Medical Center"
	sourceDef.SourceType = pkg.SourceTypeValleyMedicalCenter
	sourceDef.Category = []string{"2085R0202X", "282N00000X", "261QR1300X", "283Q00000X", "282E00000X", "207Q00000X"}
	sourceDef.Aliases = []string{"VALLEY MEDICAL CENTER", "ATRIUM HEALTH NAVICENT PRIMARY CARE FORT VALLEY"}
	sourceDef.Identifiers = map[string][]string{"http://hl7.org/fhir/sid/us-npi": []string{"1245230598", "1649209230", "1275775314", "1467699702", "1922363209", "1831543099", "1487376422"}}
	sourceDef.SecretKeyPrefix = "epic"

	return sourceDef, err
}
