// Copyright (C) Fasten Health, Inc. - All Rights Reserved.
//
// THIS FILE IS GENERATED BY https://github.com/fastenhealth/fasten-sources-gen
// PLEASE DO NOT EDIT BY HAND

package source

import (
	definitions "github.com/fastenhealth/fasten-sources/definitions"
	platform "github.com/fastenhealth/fasten-sources/definitions/internal/platform"
	models "github.com/fastenhealth/fasten-sources/definitions/models"
	pkg "github.com/fastenhealth/fasten-sources/pkg"
)

// https://esoap.mihs.org/FHIR/api/FHIR/R4/.well-known/smart-configuration
// https://esoap.mihs.org/FHIR/api/FHIR/R4/metadata
func GetSourceValleywiseHealth(env pkg.FastenEnvType) (models.LighthouseSourceDefinition, error) {
	sourceDef, err := platform.GetSourceEpic(env)
	sourceDef.AuthorizationEndpoint = "https://esoap.mihs.org/FHIR/oauth2/authorize"
	sourceDef.TokenEndpoint = "https://esoap.mihs.org/FHIR/oauth2/token"

	sourceDef.Audience = "https://esoap.mihs.org/FHIR/api/FHIR/R4"

	sourceDef.ApiEndpointBaseUrl = "https://esoap.mihs.org/FHIR/api/FHIR/R4"
	if env == pkg.FastenEnvSandbox {
		sourceDef.ClientId = ""
	}
	sourceDef.RedirectUri = pkg.GetCallbackEndpoint(string(definitions.SourceTypeEpic))

	sourceDef.Display = "Valleywise Health"
	sourceDef.SourceType = definitions.SourceTypeValleywiseHealth
	sourceDef.Enabled = true
	sourceDef.SecretKeyPrefix = "epic"

	return sourceDef, err
}
