// Copyright (C) Fasten Health, Inc. - All Rights Reserved.
//
// THIS FILE IS GENERATED BY https://github.com/fastenhealth/fasten-sources-gen
// PLEASE DO NOT EDIT BY HAND

package source

import (
	platform "github.com/fastenhealth/fasten-sources/definitions/internal/platform"
	models "github.com/fastenhealth/fasten-sources/definitions/models"
	pkg "github.com/fastenhealth/fasten-sources/pkg"
)

// https://fhir-myrecord.cerner.com/r4/eb237299-e2be-4fd4-aca6-5fa7adcd28c1/metadata
func GetSourceWalterKnoxMemorialHospital(env pkg.FastenLighthouseEnvType, clientIdLookup map[pkg.SourceType]string) (models.LighthouseSourceDefinition, error) {
	sourceDef, err := platform.GetSourceCerner(env, clientIdLookup)
	sourceDef.AuthorizationEndpoint = "https://authorization.cerner.com/tenants/eb237299-e2be-4fd4-aca6-5fa7adcd28c1/protocols/oauth2/profiles/smart-v1/personas/patient/authorize"
	sourceDef.TokenEndpoint = "https://authorization.cerner.com/tenants/eb237299-e2be-4fd4-aca6-5fa7adcd28c1/protocols/oauth2/profiles/smart-v1/token"
	sourceDef.IntrospectionEndpoint = "https://authorization.cerner.com/tokeninfo"

	sourceDef.Audience = "https://fhir-myrecord.cerner.com/r4/eb237299-e2be-4fd4-aca6-5fa7adcd28c1"

	sourceDef.ApiEndpointBaseUrl = "https://fhir-myrecord.cerner.com/r4/eb237299-e2be-4fd4-aca6-5fa7adcd28c1"
	// retrieve client-id, if available
	if clientId, clientIdOk := clientIdLookup[pkg.SourceTypeWalterKnoxMemorialHospital]; clientIdOk {
		sourceDef.ClientId = clientId
	}
	sourceDef.RedirectUri = pkg.GetCallbackEndpoint(string(pkg.SourceTypeCerner))

	sourceDef.Display = "Walter Knox Memorial Hospital"
	sourceDef.SourceType = pkg.SourceTypeWalterKnoxMemorialHospital
	sourceDef.Category = []string{"261QR1300X", "207RR0500X", "208600000X", "213ES0103X", "174400000X", "282NC0060X", "275N00000X", "261QP2300X"}
	sourceDef.Aliases = []string{"VALOR HEALTH - EMMETT MEDICAL CENTER", "VALOR HEALTH", "SURGICAL SPECIALTY CLINIC", "SWING BED"}
	sourceDef.Identifiers = map[string][]string{"http://hl7.org/fhir/sid/us-npi": []string{"1821091083", "1326206947", "1063419018", "1700909983", "1114374055", "1295193423"}}
	sourceDef.BrandLogo = "walter-knox-memorial-hospital.jpg"
	sourceDef.PatientAccessUrl = "https://www.facebook.com/walter.hospital/"
	sourceDef.SecretKeyPrefix = "cerner"

	return sourceDef, err
}
