// Copyright (C) Fasten Health, Inc. - All Rights Reserved.
//
// THIS FILE IS GENERATED BY https://github.com/fastenhealth/fasten-sources-gen
// PLEASE DO NOT EDIT BY HAND

package source

import (
	platform "github.com/fastenhealth/fasten-sources/definitions/internal/platform"
	models "github.com/fastenhealth/fasten-sources/definitions/models"
	pkg "github.com/fastenhealth/fasten-sources/pkg"
)

// https://fhir-myrecord.cerner.com/r4/be23e9e1-90d2-4a37-b049-059a92ffad6d/metadata
func GetSourceWesternMissouriMedicalCenter(env pkg.FastenLighthouseEnvType, clientIdLookup map[pkg.SourceType]string) (models.LighthouseSourceDefinition, error) {
	sourceDef, err := platform.GetSourceCerner(env, clientIdLookup)
	sourceDef.AuthorizationEndpoint = "https://authorization.cerner.com/tenants/be23e9e1-90d2-4a37-b049-059a92ffad6d/protocols/oauth2/profiles/smart-v1/personas/patient/authorize"
	sourceDef.TokenEndpoint = "https://authorization.cerner.com/tenants/be23e9e1-90d2-4a37-b049-059a92ffad6d/protocols/oauth2/profiles/smart-v1/token"
	sourceDef.IntrospectionEndpoint = "https://authorization.cerner.com/tokeninfo"

	sourceDef.Audience = "https://fhir-myrecord.cerner.com/r4/be23e9e1-90d2-4a37-b049-059a92ffad6d"

	sourceDef.ApiEndpointBaseUrl = "https://fhir-myrecord.cerner.com/r4/be23e9e1-90d2-4a37-b049-059a92ffad6d"
	// retrieve client-id, if available
	if clientId, clientIdOk := clientIdLookup[pkg.SourceTypeWesternMissouriMedicalCenter]; clientIdOk {
		sourceDef.ClientId = clientId
	}
	sourceDef.RedirectUri = pkg.GetCallbackEndpoint(string(pkg.SourceTypeCerner))

	sourceDef.Display = "Western Missouri Medical Center"
	sourceDef.SourceType = pkg.SourceTypeWesternMissouriMedicalCenter
	sourceDef.Category = []string{"207R00000X", "207RX0202X", "261QX0200X", "275N00000X", "282N00000X", "207L00000X", "207Q00000X", "261QR1300X", "273R00000X", "208VP0014X", "208800000X", "208VP0000X"}
	sourceDef.Aliases = []string{"WESTERN MISSOURI INTERNAL MEDICINE", "WESTERN MISSOURI CANCER CENTER", "WESTERN MISSOURI ANESTHESIOLOGY", "FAMILY PRACTICE OF CENTRAL MISSOURI - WARRENSBURG", "BRIDGES SENIOR BEHAVIORAL HEALTH", "WESTERN MISSOURI SPECIALTY SERVICES - UROLOGY", "WESTERN MISSOURI MEDICAL CENTER CLINICS"}
	sourceDef.Identifiers = map[string][]string{"http://hl7.org/fhir/sid/us-npi": []string{"1578876751", "1720409113", "1477128817", "1083601330", "1073500104", "1346790508", "1528516192", "1528497401", "1174105266", "1083296172"}}
	sourceDef.PatientAccessUrl = "https://wmmc.com/"
	sourceDef.SecretKeyPrefix = "cerner"

	return sourceDef, err
}
