// Copyright (C) Fasten Health, Inc. - All Rights Reserved.
//
// THIS FILE IS GENERATED BY https://github.com/fastenhealth/fasten-sources-gen
// PLEASE DO NOT EDIT BY HAND

package source

import (
	platform "github.com/fastenhealth/fasten-sources/definitions/internal/platform"
	models "github.com/fastenhealth/fasten-sources/definitions/models"
	pkg "github.com/fastenhealth/fasten-sources/pkg"
)

// https://fhir.nextgen.com/nge/prod/fhir-api-r4/fhir/r4/metadata
func GetSourceWhatleyHealthServicesInc(env pkg.FastenLighthouseEnvType, clientIdLookup map[pkg.SourceType]string) (models.LighthouseSourceDefinition, error) {
	sourceDef, err := platform.GetSourceNextgen(env, clientIdLookup)
	sourceDef.AuthorizationEndpoint = "https://fhir.nextgen.com/nge/prod/patient-oauth/authorize"
	sourceDef.TokenEndpoint = "https://fhir.nextgen.com/nge/prod/patient-oauth/token"

	sourceDef.Audience = "https://fhir.nextgen.com/nge/prod/fhir-api-r4/fhir/r4"

	sourceDef.ApiEndpointBaseUrl = "https://fhir.nextgen.com/nge/prod/fhir-api-r4/fhir/r4"
	// retrieve client-id, if available
	if clientId, clientIdOk := clientIdLookup[pkg.SourceTypeWhatleyHealthServicesInc]; clientIdOk {
		sourceDef.ClientId = clientId
	}
	sourceDef.RedirectUri = pkg.GetCallbackEndpoint(string(pkg.SourceTypeNextgen))

	sourceDef.Display = "Whatley Health Services Inc"
	sourceDef.SourceType = pkg.SourceTypeWhatleyHealthServicesInc
	sourceDef.Category = []string{"261QF0400X"}
	sourceDef.Aliases = []string{"EUTAW HEALTH CENTER", "JAMES O. ELLIS HEALTH CENTER", "LABRIDGETTE R. ELLIS MEDICAL AND DENTAL CENTER", "MAUDE L. WHATLEY HEALTH CENTERS", "OAKMAN STUDENT HEALTH AND WELLNESS CENTER", "SIPSEY HEALTH CENTER", "SUMTER COUNTY HEALTH CENTER"}
	sourceDef.Identifiers = map[string][]string{"http://hl7.org/fhir/sid/us-npi": []string{"1063422756", "1356369078", "1801817549", "1285655936", "1487104691", "1063606358", "1831133958"}}
	sourceDef.PatientAccessUrl = "https://whatleyhealth.org/"
	sourceDef.SecretKeyPrefix = "nextgen"

	return sourceDef, err
}
