// Copyright (C) Fasten Health, Inc. - All Rights Reserved.
//
// THIS FILE IS GENERATED BY https://github.com/fastenhealth/fasten-sources-gen
// PLEASE DO NOT EDIT BY HAND

package source

import (
	platform "github.com/fastenhealth/fasten-sources/definitions/internal/platform"
	models "github.com/fastenhealth/fasten-sources/definitions/models"
	pkg "github.com/fastenhealth/fasten-sources/pkg"
)

// https://fhir-myrecord.cerner.com/r4/UmST5Nz0TFWN1WTGDQw7-TwaxvLREKn_/metadata
func GetSourceWilliamOfrichterDpm(env pkg.FastenLighthouseEnvType, clientIdLookup map[pkg.SourceType]string) (models.LighthouseSourceDefinition, error) {
	sourceDef, err := platform.GetSourceCerner(env, clientIdLookup)
	sourceDef.AuthorizationEndpoint = "https://authorization.cerner.com/tenants/UmST5Nz0TFWN1WTGDQw7-TwaxvLREKn_/protocols/oauth2/profiles/smart-v1/personas/patient/authorize"
	sourceDef.TokenEndpoint = "https://authorization.cerner.com/tenants/UmST5Nz0TFWN1WTGDQw7-TwaxvLREKn_/protocols/oauth2/profiles/smart-v1/token"
	sourceDef.IntrospectionEndpoint = "https://authorization.cerner.com/tokeninfo"

	sourceDef.Audience = "https://fhir-myrecord.cerner.com/r4/UmST5Nz0TFWN1WTGDQw7-TwaxvLREKn_"

	sourceDef.ApiEndpointBaseUrl = "https://fhir-myrecord.cerner.com/r4/UmST5Nz0TFWN1WTGDQw7-TwaxvLREKn_"
	// retrieve client-id, if available
	if clientId, clientIdOk := clientIdLookup[pkg.SourceTypeWilliamOfrichterDpm]; clientIdOk {
		sourceDef.ClientId = clientId
	}
	sourceDef.RedirectUri = pkg.GetCallbackEndpoint(string(pkg.SourceTypeCerner))

	sourceDef.Display = "William Ofrichter, DPM"
	sourceDef.SourceType = pkg.SourceTypeWilliamOfrichterDpm
	sourceDef.PatientAccessUrl = "https://www.healthgrades.com/physician/dr-william-ofrichter-2kmwb"
	sourceDef.SecretKeyPrefix = "cerner"

	return sourceDef, err
}
