// Copyright (C) Fasten Health, Inc. - All Rights Reserved.
//
// THIS FILE IS GENERATED BY https://github.com/fastenhealth/fasten-sources-gen
// PLEASE DO NOT EDIT BY HAND

package factory

import (
	"context"
	"fmt"
	platform "github.com/fastenhealth/fasten-sources/clients/internal/platform"
	sandbox "github.com/fastenhealth/fasten-sources/clients/internal/sandbox"
	source "github.com/fastenhealth/fasten-sources/clients/internal/source"
	models "github.com/fastenhealth/fasten-sources/clients/models"
	pkg "github.com/fastenhealth/fasten-sources/pkg"
	logrus "github.com/sirupsen/logrus"
	"net/http"
)

func GetSourceClient(env pkg.FastenEnvType, sourceType pkg.SourceType, ctx context.Context, globalLogger logrus.FieldLogger, sourceCreds models.SourceCredential, testHttpClient ...*http.Client) (models.SourceClient, *models.SourceCredential, error) {
	switch sourceType {
	// platform
	case pkg.SourceTypeCareevolution:
		return platform.GetSourceClientCareevolution(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeCerner:
		return platform.GetSourceClientCerner(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeEpic:
		return platform.GetSourceClientEpic(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	// source
	case pkg.SourceTypeAccessCommunityHealthNetwork:
		return source.GetSourceClientAccessCommunityHealthNetwork(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeAdultAndPediatricEarNoseAndThroatKalamazoo:
		return source.GetSourceClientAdultAndPediatricEarNoseAndThroatKalamazoo(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeAdvantagecarePhysicians:
		return source.GetSourceClientAdvantagecarePhysicians(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeAdventhealth:
		return source.GetSourceClientAdventhealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeAdventistHealthWest:
		return source.GetSourceClientAdventistHealthWest(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeAkronChildrensHospital:
		return source.GetSourceClientAkronChildrensHospital(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeAlamedaHealthSystem:
		return source.GetSourceClientAlamedaHealthSystem(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeAlleghenyHealthNetwork:
		return source.GetSourceClientAlleghenyHealthNetwork(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeAllinaHealthSystem:
		return source.GetSourceClientAllinaHealthSystem(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeAltamed:
		return source.GetSourceClientAltamed(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeAltruHealthSystem:
		return source.GetSourceClientAltruHealthSystem(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeAmerigroup:
		return source.GetSourceClientAmerigroup(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeAmerigroupmedicaid:
		return source.GetSourceClientAmerigroupmedicaid(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeAnmedHealth:
		return source.GetSourceClientAnmedHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeAnnAndRobertHLurieChildrensHospitalOfChicago:
		return source.GetSourceClientAnnAndRobertHLurieChildrensHospitalOfChicago(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeAnthemMedicaid:
		return source.GetSourceClientAnthemMedicaid(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeAnthem:
		return source.GetSourceClientAnthem(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeAnthembluecrossca:
		return source.GetSourceClientAnthembluecrossca(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeArdent:
		return source.GetSourceClientArdent(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeArizonaCommunityPhysicians:
		return source.GetSourceClientArizonaCommunityPhysicians(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeArkansasChildrens:
		return source.GetSourceClientArkansasChildrens(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeArrowheadRegionalMedicalCenter:
		return source.GetSourceClientArrowheadRegionalMedicalCenter(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeAsanteHealthSystems:
		return source.GetSourceClientAsanteHealthSystems(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeAspenValleyHospital:
		return source.GetSourceClientAspenValleyHospital(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeAspirus:
		return source.GetSourceClientAspirus(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeAtlanticHealth:
		return source.GetSourceClientAtlanticHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeAtriumHealthWakeForestBaptist:
		return source.GetSourceClientAtriumHealthWakeForestBaptist(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeAtriumHealth:
		return source.GetSourceClientAtriumHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeAtriusHealth:
		return source.GetSourceClientAtriusHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeAuroraHealthCareMyaurora:
		return source.GetSourceClientAuroraHealthCareMyaurora(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeAustinRegionalClinic:
		return source.GetSourceClientAustinRegionalClinic(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeBalladHealth:
		return source.GetSourceClientBalladHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeBaptistHealthArkansas:
		return source.GetSourceClientBaptistHealthArkansas(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeBaptistHealthKyAndIn:
		return source.GetSourceClientBaptistHealthKyAndIn(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeBaptistHealthNortheastFlorida:
		return source.GetSourceClientBaptistHealthNortheastFlorida(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeBaptistMemorialHealthCare:
		return source.GetSourceClientBaptistMemorialHealthCare(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeBassettHealthcare:
		return source.GetSourceClientBassettHealthcare(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeBaycareClinicMybaycare:
		return source.GetSourceClientBaycareClinicMybaycare(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeBayhealthMedicalCenter:
		return source.GetSourceClientBayhealthMedicalCenter(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeBaylorCollegeOfMedicine:
		return source.GetSourceClientBaylorCollegeOfMedicine(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeBaylorScottAndWhite:
		return source.GetSourceClientBaylorScottAndWhite(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeBcbskansas:
		return source.GetSourceClientBcbskansas(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeBcbskansasmedicare:
		return source.GetSourceClientBcbskansasmedicare(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeBcbsny:
		return source.GetSourceClientBcbsny(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeBeaumontHealth:
		return source.GetSourceClientBeaumontHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeBellinHealth:
		return source.GetSourceClientBellinHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeBjcAndWashingtonUniversity:
		return source.GetSourceClientBjcAndWashingtonUniversity(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeBluemedicareadvantage:
		return source.GetSourceClientBluemedicareadvantage(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeBonSecoursHealthSystem:
		return source.GetSourceClientBonSecoursHealthSystem(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeBostonMedicalCenter:
		return source.GetSourceClientBostonMedicalCenter(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeBoulderCommunityHealth:
		return source.GetSourceClientBoulderCommunityHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeBronsonHealthcareGroup:
		return source.GetSourceClientBronsonHealthcareGroup(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeBrookwoodBaptistHealth:
		return source.GetSourceClientBrookwoodBaptistHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeBrownAndTolandPhysicians:
		return source.GetSourceClientBrownAndTolandPhysicians(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeBryanHealth:
		return source.GetSourceClientBryanHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeBuffaloMedicalGroup:
		return source.GetSourceClientBuffaloMedicalGroup(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeCapeCodHealthcare:
		return source.GetSourceClientCapeCodHealthcare(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeCapeFearValleyHealth:
		return source.GetSourceClientCapeFearValleyHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeCareNewEngland:
		return source.GetSourceClientCareNewEngland(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeCarleFoundationHospitalAndPhysicianGroup:
		return source.GetSourceClientCarleFoundationHospitalAndPhysicianGroup(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeCaromontHealth:
		return source.GetSourceClientCaromontHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeCatholicHealthLongIslandNy:
		return source.GetSourceClientCatholicHealthLongIslandNy(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeCatholicHealthSystemBuffalo:
		return source.GetSourceClientCatholicHealthSystemBuffalo(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeCedarsSinaiHealthSystem:
		return source.GetSourceClientCedarsSinaiHealthSystem(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeCentracareHealthAndAffiliates:
		return source.GetSourceClientCentracareHealthAndAffiliates(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeCenturaHealth:
		return source.GetSourceClientCenturaHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeCharlotteEyeEarNoseAndThroatAssociates:
		return source.GetSourceClientCharlotteEyeEarNoseAndThroatAssociates(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeChesapeakeRegionalMedicalCenter:
		return source.GetSourceClientChesapeakeRegionalMedicalCenter(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeCheyenneRegionalMedicalCenter:
		return source.GetSourceClientCheyenneRegionalMedicalCenter(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeChildrensHealthSystemOfTexas:
		return source.GetSourceClientChildrensHealthSystemOfTexas(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeChildrensHospitalAndMedicalCenterOmahaNebraska:
		return source.GetSourceClientChildrensHospitalAndMedicalCenterOmahaNebraska(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeChildrensHospitalColorado:
		return source.GetSourceClientChildrensHospitalColorado(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeChildrensHospitalOfPhiladelphia:
		return source.GetSourceClientChildrensHospitalOfPhiladelphia(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeChildrensWisconsin:
		return source.GetSourceClientChildrensWisconsin(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeChildrenssHealthcareOfAtlanta:
		return source.GetSourceClientChildrenssHealthcareOfAtlanta(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeCignaMedicalGroup:
		return source.GetSourceClientCignaMedicalGroup(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeCincinnatiChildrensHospitalMedicalCenter:
		return source.GetSourceClientCincinnatiChildrensHospitalMedicalCenter(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeCityOfHope:
		return source.GetSourceClientCityOfHope(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeClearhealthalliance:
		return source.GetSourceClientClearhealthalliance(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeClevelandClinic:
		return source.GetSourceClientClevelandClinic(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeColumbiaPhysicians:
		return source.GetSourceClientColumbiaPhysicians(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeColumbusRegionalHealth:
		return source.GetSourceClientColumbusRegionalHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeCommunityHealthNetwork:
		return source.GetSourceClientCommunityHealthNetwork(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeCommunityHealthcareSystem:
		return source.GetSourceClientCommunityHealthcareSystem(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeCommunityMedicalCenters:
		return source.GetSourceClientCommunityMedicalCenters(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeConeHealth:
		return source.GetSourceClientConeHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeConemaughHealthSystem:
		return source.GetSourceClientConemaughHealthSystem(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeConfluenceHealth:
		return source.GetSourceClientConfluenceHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeConnecticutChildrensMedicalCenter:
		return source.GetSourceClientConnecticutChildrensMedicalCenter(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeContraCosta:
		return source.GetSourceClientContraCosta(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeCookChildrensHealthCareSystem:
		return source.GetSourceClientCookChildrensHealthCareSystem(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeCooperUniversityHealthCare:
		return source.GetSourceClientCooperUniversityHealthCare(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeCottageHealth:
		return source.GetSourceClientCottageHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeCovenantHealth:
		return source.GetSourceClientCovenantHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeDartmouthHitchcock:
		return source.GetSourceClientDartmouthHitchcock(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeDavitaPhysicianSolutions:
		return source.GetSourceClientDavitaPhysicianSolutions(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeDaytonChildrensHospital:
		return source.GetSourceClientDaytonChildrensHospital(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeDeaconessHealthSystemPrd:
		return source.GetSourceClientDeaconessHealthSystemPrd(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeDellchildrens:
		return source.GetSourceClientDellchildrens(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeDenverHealth:
		return source.GetSourceClientDenverHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeDrexelMedicine:
		return source.GetSourceClientDrexelMedicine(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeDriscollChildrensHospital:
		return source.GetSourceClientDriscollChildrensHospital(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeDukeHealth:
		return source.GetSourceClientDukeHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeDulyHealthAndCare:
		return source.GetSourceClientDulyHealthAndCare(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeEastBostonNeighborhoodHealthCenter:
		return source.GetSourceClientEastBostonNeighborhoodHealthCenter(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeEdwardElmhurstHealthcare:
		return source.GetSourceClientEdwardElmhurstHealthcare(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeEisenhowerMedicalCenter:
		return source.GetSourceClientEisenhowerMedicalCenter(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeElCaminoHospital:
		return source.GetSourceClientElCaminoHospital(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeElRioHealth:
		return source.GetSourceClientElRioHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeEmoryHealthcare:
		return source.GetSourceClientEmoryHealthcare(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeEmpireblue:
		return source.GetSourceClientEmpireblue(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeEmpirebluemedicaid:
		return source.GetSourceClientEmpirebluemedicaid(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeEnglewoodHospitalAndMedicalCenter:
		return source.GetSourceClientEnglewoodHospitalAndMedicalCenter(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeEnloeMedicalCenter:
		return source.GetSourceClientEnloeMedicalCenter(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeErlangerHealthSystem:
		return source.GetSourceClientErlangerHealthSystem(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeEskenaziHealth:
		return source.GetSourceClientEskenaziHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeEssentiaHealth:
		return source.GetSourceClientEssentiaHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeEvernorth:
		return source.GetSourceClientEvernorth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeFairviewHealthServices:
		return source.GetSourceClientFairviewHealthServices(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeFamilyHealthCenterMichigan:
		return source.GetSourceClientFamilyHealthCenterMichigan(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeFastmed:
		return source.GetSourceClientFastmed(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeFirsthealthOfTheCarolinas:
		return source.GetSourceClientFirsthealthOfTheCarolinas(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeFranciscanAlliance:
		return source.GetSourceClientFranciscanAlliance(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeFranciscanMissionariesOfOurLadyHealthSystem:
		return source.GetSourceClientFranciscanMissionariesOfOurLadyHealthSystem(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeFreseniusMedicalCareNorthAmerica:
		return source.GetSourceClientFreseniusMedicalCareNorthAmerica(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeFroedtertHealth:
		return source.GetSourceClientFroedtertHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeGarnetHealth:
		return source.GetSourceClientGarnetHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeGeisinger:
		return source.GetSourceClientGeisinger(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeGenesisHealthcareSystem:
		return source.GetSourceClientGenesisHealthcareSystem(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeGeorgeWashingtonUniversityMedicalFacultyAssociates:
		return source.GetSourceClientGeorgeWashingtonUniversityMedicalFacultyAssociates(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeGoldenValleyHealthCenters:
		return source.GetSourceClientGoldenValleyHealthCenters(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeGradyHealthSystem:
		return source.GetSourceClientGradyHealthSystem(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeGreaterBaltimoreMedicalCenter:
		return source.GetSourceClientGreaterBaltimoreMedicalCenter(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeGroupHealthCooperativeSouthCentralWisconsin:
		return source.GetSourceClientGroupHealthCooperativeSouthCentralWisconsin(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeGundersenHealthSystem:
		return source.GetSourceClientGundersenHealthSystem(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeHackensackMeridianHealth:
		return source.GetSourceClientHackensackMeridianHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeHartfordHealthcare:
		return source.GetSourceClientHartfordHealthcare(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeHattiesburgClinicAndForrestGeneralHospital:
		return source.GetSourceClientHattiesburgClinicAndForrestGeneralHospital(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeHawaiiPacificHealthPrd:
		return source.GetSourceClientHawaiiPacificHealthPrd(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeHcaCentralAndWestTexas:
		return source.GetSourceClientHcaCentralAndWestTexas(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeHcaMountain:
		return source.GetSourceClientHcaMountain(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeHcaSouthAtlantic:
		return source.GetSourceClientHcaSouthAtlantic(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeHealthpartners:
		return source.GetSourceClientHealthpartners(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeHealthybluela:
		return source.GetSourceClientHealthybluela(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeHealthybluelamedicaid:
		return source.GetSourceClientHealthybluelamedicaid(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeHealthybluemo:
		return source.GetSourceClientHealthybluemo(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeHealthybluemomedicaid:
		return source.GetSourceClientHealthybluemomedicaid(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeHealthybluenc:
		return source.GetSourceClientHealthybluenc(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeHealthybluencmedicaid:
		return source.GetSourceClientHealthybluencmedicaid(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeHealthybluene:
		return source.GetSourceClientHealthybluene(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeHealthybluesc:
		return source.GetSourceClientHealthybluesc(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeHendricksRegionalHealth:
		return source.GetSourceClientHendricksRegionalHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeHennepinHealthcare:
		return source.GetSourceClientHennepinHealthcare(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeHenryFordHealthSystem:
		return source.GetSourceClientHenryFordHealthSystem(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeHighmarkwesternny:
		return source.GetSourceClientHighmarkwesternny(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeHillPhysicians:
		return source.GetSourceClientHillPhysicians(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeHoagMemorialHospitalPresbyterian:
		return source.GetSourceClientHoagMemorialHospitalPresbyterian(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeHonorhealth:
		return source.GetSourceClientHonorhealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeHospitalForSpecialSurgery:
		return source.GetSourceClientHospitalForSpecialSurgery(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeHospitalSistersHealthSystemHshs:
		return source.GetSourceClientHospitalSistersHealthSystemHshs(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeHoustonMethodist:
		return source.GetSourceClientHoustonMethodist(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeHurleyMedicalCenter:
		return source.GetSourceClientHurleyMedicalCenter(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeIllinoisBoneAndJointInstitute:
		return source.GetSourceClientIllinoisBoneAndJointInstitute(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeInfirmaryHealth:
		return source.GetSourceClientInfirmaryHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeInovaAndValleyHealth:
		return source.GetSourceClientInovaAndValleyHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeInstituteForFamilyHealth:
		return source.GetSourceClientInstituteForFamilyHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeIntegrisHealth:
		return source.GetSourceClientIntegrisHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeJeffersonHealth:
		return source.GetSourceClientJeffersonHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeJohnMuirHealth:
		return source.GetSourceClientJohnMuirHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeJohnsHopkinsMedicine:
		return source.GetSourceClientJohnsHopkinsMedicine(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeJpsHealthNetwork:
		return source.GetSourceClientJpsHealthNetwork(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeKaiserPermanenteCaliforniaNorthern:
		return source.GetSourceClientKaiserPermanenteCaliforniaNorthern(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeKaiserPermanenteCaliforniaSouthern:
		return source.GetSourceClientKaiserPermanenteCaliforniaSouthern(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeKaiserPermanenteColorado:
		return source.GetSourceClientKaiserPermanenteColorado(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeKaiserPermanenteGeorgia:
		return source.GetSourceClientKaiserPermanenteGeorgia(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeKaiserPermanenteHawaiiMauiHealthSystem:
		return source.GetSourceClientKaiserPermanenteHawaiiMauiHealthSystem(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeKaiserPermanenteMarylandVirginiaWashingtonDC:
		return source.GetSourceClientKaiserPermanenteMarylandVirginiaWashingtonDC(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeKaiserPermanenteOregonSwWashington:
		return source.GetSourceClientKaiserPermanenteOregonSwWashington(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeKaiserPermanenteWashington:
		return source.GetSourceClientKaiserPermanenteWashington(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeKalamazooCollegeStudentHealthCenter:
		return source.GetSourceClientKalamazooCollegeStudentHealthCenter(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeKalamazooFootSurgery:
		return source.GetSourceClientKalamazooFootSurgery(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeKelseySeyboldClinic:
		return source.GetSourceClientKelseySeyboldClinic(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeKennedyKriegerInstitute:
		return source.GetSourceClientKennedyKriegerInstitute(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeKetteringHealthNetwork:
		return source.GetSourceClientKetteringHealthNetwork(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeKingsDaughtersMedicalCenter:
		return source.GetSourceClientKingsDaughtersMedicalCenter(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeKootenaiHealth:
		return source.GetSourceClientKootenaiHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeLacyCKesslerMdPa:
		return source.GetSourceClientLacyCKesslerMdPa(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeLaheyHealthSystem:
		return source.GetSourceClientLaheyHealthSystem(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeLakelandHealth:
		return source.GetSourceClientLakelandHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeLancasterGeneralHealth:
		return source.GetSourceClientLancasterGeneralHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeLcmcHealth:
		return source.GetSourceClientLcmcHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeLeeHealth:
		return source.GetSourceClientLeeHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeLegacyHealth:
		return source.GetSourceClientLegacyHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeLehighValleyHealthNetwork:
		return source.GetSourceClientLehighValleyHealthNetwork(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeLeonMedicalCenters:
		return source.GetSourceClientLeonMedicalCenters(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeLickingMemorialHealthSystems:
		return source.GetSourceClientLickingMemorialHealthSystems(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeLifespan:
		return source.GetSourceClientLifespan(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeLomaLindaUniversityHealthAndCareconnectPartners:
		return source.GetSourceClientLomaLindaUniversityHealthAndCareconnectPartners(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeLoyolaMedicine:
		return source.GetSourceClientLoyolaMedicine(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeLuminisHealth:
		return source.GetSourceClientLuminisHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeMainLineHealth:
		return source.GetSourceClientMainLineHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeMainehealth:
		return source.GetSourceClientMainehealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeMartinHealthSystem:
		return source.GetSourceClientMartinHealthSystem(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeMaryGreeleyMedicalCenterIowa:
		return source.GetSourceClientMaryGreeleyMedicalCenterIowa(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeMaryWashingtonHealthcare:
		return source.GetSourceClientMaryWashingtonHealthcare(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeMassGeneralBrigham:
		return source.GetSourceClientMassGeneralBrigham(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeMayoClinic:
		return source.GetSourceClientMayoClinic(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeMcfarlandClinicIowa:
		return source.GetSourceClientMcfarlandClinicIowa(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeMedicalUniversityOfSouthCarolina:
		return source.GetSourceClientMedicalUniversityOfSouthCarolina(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeMedisysHealthNetwork:
		return source.GetSourceClientMedisysHealthNetwork(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeMemorialHealthcareSystem:
		return source.GetSourceClientMemorialHealthcareSystem(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeMemorialHospitalAndHealthCareCenter:
		return source.GetSourceClientMemorialHospitalAndHealthCareCenter(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeMemorialcare:
		return source.GetSourceClientMemorialcare(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeMercyHealthOhKy:
		return source.GetSourceClientMercyHealthOhKy(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeMercyHealthServicesMd:
		return source.GetSourceClientMercyHealthServicesMd(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeMercyHealthSystemWi:
		return source.GetSourceClientMercyHealthSystemWi(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeMercyMedicalCenter:
		return source.GetSourceClientMercyMedicalCenter(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeMeritus:
		return source.GetSourceClientMeritus(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeMethodistHealthSystem:
		return source.GetSourceClientMethodistHealthSystem(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeMethodistHospitalsPrd:
		return source.GetSourceClientMethodistHospitalsPrd(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeMetroHealthMichigan:
		return source.GetSourceClientMetroHealthMichigan(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeMetrohealthOh:
		return source.GetSourceClientMetrohealthOh(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeMichiganMedicine:
		return source.GetSourceClientMichiganMedicine(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeMiddlesexHospital:
		return source.GetSourceClientMiddlesexHospital(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeMidmichiganHealth:
		return source.GetSourceClientMidmichiganHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeMohawkValleyHealthSystem:
		return source.GetSourceClientMohawkValleyHealthSystem(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeMolinaHealthcare:
		return source.GetSourceClientMolinaHealthcare(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeMontageHealth:
		return source.GetSourceClientMontageHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeMontefioreMedicalCenter:
		return source.GetSourceClientMontefioreMedicalCenter(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeMonumentHealth:
		return source.GetSourceClientMonumentHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeMountAuburnHospital:
		return source.GetSourceClientMountAuburnHospital(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeMountSinaiHealthSystem:
		return source.GetSourceClientMountSinaiHealthSystem(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeMountSinaiMedicalCenter:
		return source.GetSourceClientMountSinaiMedicalCenter(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeMulticareHealthSystem:
		return source.GetSourceClientMulticareHealthSystem(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeMuscogeeCreekNationDepartmentOfHealth:
		return source.GetSourceClientMuscogeeCreekNationDepartmentOfHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeMyDrNow:
		return source.GetSourceClientMyDrNow(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeNationwideChildrensHospital:
		return source.GetSourceClientNationwideChildrensHospital(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeNchHealthcareSystem:
		return source.GetSourceClientNchHealthcareSystem(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeNebraskaMedicine:
		return source.GetSourceClientNebraskaMedicine(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeNemours:
		return source.GetSourceClientNemours(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeNephrologyCenterSouthwestMichigan:
		return source.GetSourceClientNephrologyCenterSouthwestMichigan(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeNewHanoverRegionalMedicalCenter:
		return source.GetSourceClientNewHanoverRegionalMedicalCenter(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeNewJerseyUrology:
		return source.GetSourceClientNewJerseyUrology(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeNewYorkPresbyterian:
		return source.GetSourceClientNewYorkPresbyterian(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeNorthMemorialHealth:
		return source.GetSourceClientNorthMemorialHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeNorthMississippiHealthServices:
		return source.GetSourceClientNorthMississippiHealthServices(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeNorthOaks:
		return source.GetSourceClientNorthOaks(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeNortheastGeorgiaHealthSystem:
		return source.GetSourceClientNortheastGeorgiaHealthSystem(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeNorthshoreUniversityHealthSystem:
		return source.GetSourceClientNorthshoreUniversityHealthSystem(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeNorthwestCommunityHospital:
		return source.GetSourceClientNorthwestCommunityHospital(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeNortonHealthcare:
		return source.GetSourceClientNortonHealthcare(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeNovantHealth:
		return source.GetSourceClientNovantHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeNovoHealth:
		return source.GetSourceClientNovoHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeNycHealthHospitals:
		return source.GetSourceClientNycHealthHospitals(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeNyuLangoneMedicalCenter:
		return source.GetSourceClientNyuLangoneMedicalCenter(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeObGynAssociatesOfWacoDrRisterDrKoeritz:
		return source.GetSourceClientObGynAssociatesOfWacoDrRisterDrKoeritz(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeOchin:
		return source.GetSourceClientOchin(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeOchsnerHealthSystem:
		return source.GetSourceClientOchsnerHealthSystem(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeOhiohealth:
		return source.GetSourceClientOhiohealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeOlmstedMedicalCenter:
		return source.GetSourceClientOlmstedMedicalCenter(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeOneBrooklynHealthSystem:
		return source.GetSourceClientOneBrooklynHealthSystem(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeOptumcareEast:
		return source.GetSourceClientOptumcareEast(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeOptumcareWest:
		return source.GetSourceClientOptumcareWest(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeOregonHealthAndScienceUniversity:
		return source.GetSourceClientOregonHealthAndScienceUniversity(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeOrlandoHealth:
		return source.GetSourceClientOrlandoHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeOrthocarolina:
		return source.GetSourceClientOrthocarolina(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeOrthovirginia:
		return source.GetSourceClientOrthovirginia(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeOsfHealthcare:
		return source.GetSourceClientOsfHealthcare(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeOverlakeHospitalMedicalCenter:
		return source.GetSourceClientOverlakeHospitalMedicalCenter(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeOwensboroHealth:
		return source.GetSourceClientOwensboroHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypePacificDentalServices:
		return source.GetSourceClientPacificDentalServices(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypePalosHealth:
		return source.GetSourceClientPalosHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeParkland:
		return source.GetSourceClientParkland(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeParkviewHealth:
		return source.GetSourceClientParkviewHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypePeacehealth:
		return source.GetSourceClientPeacehealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypePediatricPhysiciansOrganizationAtChildrens:
		return source.GetSourceClientPediatricPhysiciansOrganizationAtChildrens(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypePennMedicine:
		return source.GetSourceClientPennMedicine(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypePhelpsHealth:
		return source.GetSourceClientPhelpsHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypePiedmontHealthcare:
		return source.GetSourceClientPiedmontHealthcare(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypePikevilleMedicalCenter:
		return source.GetSourceClientPikevilleMedicalCenter(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypePineRestChristianMentalHealthServices:
		return source.GetSourceClientPineRestChristianMentalHealthServices(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypePlannedParenthood:
		return source.GetSourceClientPlannedParenthood(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypePremierHealth:
		return source.GetSourceClientPremierHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypePresbyterianHealthcareServices:
		return source.GetSourceClientPresbyterianHealthcareServices(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypePrimeHealthcare:
		return source.GetSourceClientPrimeHealthcare(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypePrismaHealth:
		return source.GetSourceClientPrismaHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeProhealthCare:
		return source.GetSourceClientProhealthCare(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypePromedicaHealthSystem:
		return source.GetSourceClientPromedicaHealthSystem(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeProvidenceHealthAndServicesAlaska:
		return source.GetSourceClientProvidenceHealthAndServicesAlaska(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeProvidenceHealthAndServicesOregonCalifornia:
		return source.GetSourceClientProvidenceHealthAndServicesOregonCalifornia(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeProvidenceHealthAndServicesWashingtonMontana:
		return source.GetSourceClientProvidenceHealthAndServicesWashingtonMontana(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeQuadmed:
		return source.GetSourceClientQuadmed(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeRadyChildrens:
		return source.GetSourceClientRadyChildrens(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeReidHealth:
		return source.GetSourceClientReidHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeReliantMedicalGroup:
		return source.GetSourceClientReliantMedicalGroup(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeRenownBartonCvmc:
		return source.GetSourceClientRenownBartonCvmc(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeRiversideHealthSystemNewportNewsVa:
		return source.GetSourceClientRiversideHealthSystemNewportNewsVa(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeRiversideMedicalCenter:
		return source.GetSourceClientRiversideMedicalCenter(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeRiversideMedicalClinic:
		return source.GetSourceClientRiversideMedicalClinic(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeRochesterRegionalHealth:
		return source.GetSourceClientRochesterRegionalHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeRushUniversityMedicalCenter:
		return source.GetSourceClientRushUniversityMedicalCenter(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeRwjbarnabasHealth:
		return source.GetSourceClientRwjbarnabasHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeSaintFrancisHealthSystem:
		return source.GetSourceClientSaintFrancisHealthSystem(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeSaintFrancisHealthcareSystemManual:
		return source.GetSourceClientSaintFrancisHealthcareSystemManual(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeSalemHealth:
		return source.GetSourceClientSalemHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeSalinasValleyMemorialHealthcareSystems:
		return source.GetSourceClientSalinasValleyMemorialHealthcareSystems(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeSamaritanHealthServices:
		return source.GetSourceClientSamaritanHealthServices(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeSanFranciscoDepartmentOfPublicHealth:
		return source.GetSourceClientSanFranciscoDepartmentOfPublicHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeSanfordHealth:
		return source.GetSourceClientSanfordHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeSansumClinic:
		return source.GetSourceClientSansumClinic(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeSantaClaraValleyMedicalCenterHospitalsAndClinics:
		return source.GetSourceClientSantaClaraValleyMedicalCenterHospitalsAndClinics(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeSclHealth:
		return source.GetSourceClientSclHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeScotlandHealthCareSystem:
		return source.GetSourceClientScotlandHealthCareSystem(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeScottishRiteForChildren:
		return source.GetSourceClientScottishRiteForChildren(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeScrippsHealth:
		return source.GetSourceClientScrippsHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeSeattleChildrensHospital:
		return source.GetSourceClientSeattleChildrensHospital(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeSelectMedical:
		return source.GetSourceClientSelectMedical(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeSelfRegionalHealthcare:
		return source.GetSourceClientSelfRegionalHealthcare(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeSentaraHealthcare:
		return source.GetSourceClientSentaraHealthcare(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeShannonHealth:
		return source.GetSourceClientShannonHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeSimplyhealthcaremedicaid:
		return source.GetSourceClientSimplyhealthcaremedicaid(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeSimplyhealthcaremedicare:
		return source.GetSourceClientSimplyhealthcaremedicare(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeSingingRiverHealthSystemPrd:
		return source.GetSourceClientSingingRiverHealthSystemPrd(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeSkagitRegionalHealth:
		return source.GetSourceClientSkagitRegionalHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeSolutionhealth:
		return source.GetSourceClientSolutionhealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeSouthGeorgiaMedicalCenter:
		return source.GetSourceClientSouthGeorgiaMedicalCenter(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeSouthShoreHealthSystem:
		return source.GetSourceClientSouthShoreHealthSystem(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeSouthcoastHealth:
		return source.GetSourceClientSouthcoastHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeSoutheastHealth:
		return source.GetSourceClientSoutheastHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeSoutheasternHealth:
		return source.GetSourceClientSoutheasternHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeSouthernIllinoisHealthcare:
		return source.GetSourceClientSouthernIllinoisHealthcare(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeSparrowHealthSystem:
		return source.GetSourceClientSparrowHealthSystem(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeSpartanburgRegionalHealthSystems:
		return source.GetSourceClientSpartanburgRegionalHealthSystems(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeSpectrumHealthLakeland:
		return source.GetSourceClientSpectrumHealthLakeland(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeSpectrumHealth:
		return source.GetSourceClientSpectrumHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeSsmHealth:
		return source.GetSourceClientSsmHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeStCharlesHealthSystem:
		return source.GetSourceClientStCharlesHealthSystem(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeStElizabethHealthcare:
		return source.GetSourceClientStElizabethHealthcare(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeStJosephHospitalHealthCenter:
		return source.GetSourceClientStJosephHospitalHealthCenter(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeStJudeChildrensResearchHospital:
		return source.GetSourceClientStJudeChildrensResearchHospital(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeStLukesHealthSystemIdahoAndEasternOregon:
		return source.GetSourceClientStLukesHealthSystemIdahoAndEasternOregon(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeStLukesHospitalNorthCarolina:
		return source.GetSourceClientStLukesHospitalNorthCarolina(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeStanfordChildrensHealth:
		return source.GetSourceClientStanfordChildrensHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeStanfordHealthCare:
		return source.GetSourceClientStanfordHealthCare(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeStormontVailHealth:
		return source.GetSourceClientStormontVailHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeSummitHealth:
		return source.GetSourceClientSummitHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeSummitcommunitycare:
		return source.GetSourceClientSummitcommunitycare(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeSunyUpstateMedicalUniversity:
		return source.GetSourceClientSunyUpstateMedicalUniversity(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeSutterHealth:
		return source.GetSourceClientSutterHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeTampaGeneralHospital:
		return source.GetSourceClientTampaGeneralHospital(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeTannerHealthSystem:
		return source.GetSourceClientTannerHealthSystem(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeTemplehealth:
		return source.GetSourceClientTemplehealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeTexasChildrens:
		return source.GetSourceClientTexasChildrens(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeTexasHealthResources:
		return source.GetSourceClientTexasHealthResources(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeTheBrooklynHospitalCenter:
		return source.GetSourceClientTheBrooklynHospitalCenter(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeTheChristHospital:
		return source.GetSourceClientTheChristHospital(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeTheEverettClinic:
		return source.GetSourceClientTheEverettClinic(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeTheGuthrieClinic:
		return source.GetSourceClientTheGuthrieClinic(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeTheOhioStateUniversityWexnerMedicalCenter:
		return source.GetSourceClientTheOhioStateUniversityWexnerMedicalCenter(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeThePolyclinic:
		return source.GetSourceClientThePolyclinic(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeThePortlandClinic:
		return source.GetSourceClientThePortlandClinic(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeTheQueensHealthSystems:
		return source.GetSourceClientTheQueensHealthSystems(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeTheUniversityOfTexasHealthScienceCenterAtHouston:
		return source.GetSourceClientTheUniversityOfTexasHealthScienceCenterAtHouston(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeTheUniversityOfTexasMdAndersonCancerCenter:
		return source.GetSourceClientTheUniversityOfTexasMdAndersonCancerCenter(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeTheUniversityOfVermontHealthNetwork:
		return source.GetSourceClientTheUniversityOfVermontHealthNetwork(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeTheVancouverClinic:
		return source.GetSourceClientTheVancouverClinic(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeThedacare:
		return source.GetSourceClientThedacare(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeTidalhealth:
		return source.GetSourceClientTidalhealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeTmcHealthcare:
		return source.GetSourceClientTmcHealthcare(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeTowerHealth:
		return source.GetSourceClientTowerHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeTrihealth:
		return source.GetSourceClientTrihealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeTrinityHealthOfNewEnglandMedicalGroupSpringfield:
		return source.GetSourceClientTrinityHealthOfNewEnglandMedicalGroupSpringfield(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeTrinityHealthOfNewEngland:
		return source.GetSourceClientTrinityHealthOfNewEngland(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeTrinityHealth:
		return source.GetSourceClientTrinityHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeTuftsMedicine:
		return source.GetSourceClientTuftsMedicine(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeUcDavisMmc:
		return source.GetSourceClientUcDavisMmc(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeUcDavis:
		return source.GetSourceClientUcDavis(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeUcHealth:
		return source.GetSourceClientUcHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeUchicagoMedicine:
		return source.GetSourceClientUchicagoMedicine(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeUclaMedicalCenter:
		return source.GetSourceClientUclaMedicalCenter(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeUconnHealth:
		return source.GetSourceClientUconnHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeUcsfBenioffChildrensHospital:
		return source.GetSourceClientUcsfBenioffChildrensHospital(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeUcsfHealth:
		return source.GetSourceClientUcsfHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeUfHealth:
		return source.GetSourceClientUfHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeUhsSanAntonio:
		return source.GetSourceClientUhsSanAntonio(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeUiHealth:
		return source.GetSourceClientUiHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeUkHealthcare:
		return source.GetSourceClientUkHealthcare(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeUmassMemorialHealthCare:
		return source.GetSourceClientUmassMemorialHealthCare(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeUmcSouthernNevada:
		return source.GetSourceClientUmcSouthernNevada(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeUncHealthCare:
		return source.GetSourceClientUncHealthCare(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeUnicare:
		return source.GetSourceClientUnicare(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeUnicarema:
		return source.GetSourceClientUnicarema(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeUnitedHealthServicesNewYorkNyuhs:
		return source.GetSourceClientUnitedHealthServicesNewYorkNyuhs(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeUnitedRegionalHealthCareSystem:
		return source.GetSourceClientUnitedRegionalHealthCareSystem(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeUnitypointHealth:
		return source.GetSourceClientUnitypointHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeUniversityHealthCareSystem:
		return source.GetSourceClientUniversityHealthCareSystem(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeUniversityHospitalNewJersey:
		return source.GetSourceClientUniversityHospitalNewJersey(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeUniversityOfArkansasForMedicalSciences:
		return source.GetSourceClientUniversityOfArkansasForMedicalSciences(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeUniversityOfCaliforniaIrvine:
		return source.GetSourceClientUniversityOfCaliforniaIrvine(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeUniversityOfCaliforniaSanDiego:
		return source.GetSourceClientUniversityOfCaliforniaSanDiego(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeUniversityOfIowaHealthCare:
		return source.GetSourceClientUniversityOfIowaHealthCare(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeUniversityOfKansasHealthSystem:
		return source.GetSourceClientUniversityOfKansasHealthSystem(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeUniversityOfLouisvillePhysicians:
		return source.GetSourceClientUniversityOfLouisvillePhysicians(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeUniversityOfMarylandMedicalSystem:
		return source.GetSourceClientUniversityOfMarylandMedicalSystem(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeUniversityOfMississippiMedicalCenter:
		return source.GetSourceClientUniversityOfMississippiMedicalCenter(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeUniversityOfPittsburghMedicalCenterUpmc:
		return source.GetSourceClientUniversityOfPittsburghMedicalCenterUpmc(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeUniversityOfRochesterMedicalCenterPrd:
		return source.GetSourceClientUniversityOfRochesterMedicalCenterPrd(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeUniversityOfTexasMedicalBranch:
		return source.GetSourceClientUniversityOfTexasMedicalBranch(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeUniversityOfTexasSouthwesternMedicalCenter:
		return source.GetSourceClientUniversityOfTexasSouthwesternMedicalCenter(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeUniversityOfToledo:
		return source.GetSourceClientUniversityOfToledo(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeUniversityOfUtahHealthcare:
		return source.GetSourceClientUniversityOfUtahHealthcare(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeUpmcCentralPa:
		return source.GetSourceClientUpmcCentralPa(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeUtHealthSanAntonio:
		return source.GetSourceClientUtHealthSanAntonio(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeUvaHealthSystem:
		return source.GetSourceClientUvaHealthSystem(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeUwHealthAndAffiliatesWisconsin:
		return source.GetSourceClientUwHealthAndAffiliatesWisconsin(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeUwMedicineWashington:
		return source.GetSourceClientUwMedicineWashington(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeValleyChildrensHealthcare:
		return source.GetSourceClientValleyChildrensHealthcare(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeValleyMedicalCenter:
		return source.GetSourceClientValleyMedicalCenter(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeValleywiseHealth:
		return source.GetSourceClientValleywiseHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeVanderbilt:
		return source.GetSourceClientVanderbilt(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeVcuHealth:
		return source.GetSourceClientVcuHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeVidantHealth:
		return source.GetSourceClientVidantHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeVirginiaHospitalCenter:
		return source.GetSourceClientVirginiaHospitalCenter(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeVirtuaHealth:
		return source.GetSourceClientVirtuaHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeWacoFamilyMedicineHeartOfTexasCommunityHealthCenter:
		return source.GetSourceClientWacoFamilyMedicineHeartOfTexasCommunityHealthCenter(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeWakemedHealthAndHospitals:
		return source.GetSourceClientWakemedHealthAndHospitals(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeWalmart:
		return source.GetSourceClientWalmart(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeWashingtonHospitalHealthcareSystem:
		return source.GetSourceClientWashingtonHospitalHealthcareSystem(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeWatsonClinic:
		return source.GetSourceClientWatsonClinic(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeWeillCornellMedicine:
		return source.GetSourceClientWeillCornellMedicine(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeWellspanHealth:
		return source.GetSourceClientWellspanHealth(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeWellstar:
		return source.GetSourceClientWellstar(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeWestTennesseeHealthcare:
		return source.GetSourceClientWestTennesseeHealthcare(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeWestVirginiaUniversityMedicine:
		return source.GetSourceClientWestVirginiaUniversityMedicine(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeWesternMichiganUniversitySchoolOfMedicine:
		return source.GetSourceClientWesternMichiganUniversitySchoolOfMedicine(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeYakimaValleyFarmWorkersClinic:
		return source.GetSourceClientYakimaValleyFarmWorkersClinic(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeYaleNewHavenHealthSystem:
		return source.GetSourceClientYaleNewHavenHealthSystem(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeYumaRegionalMedicalCenter:
		return source.GetSourceClientYumaRegionalMedicalCenter(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeAetna:
		return source.GetSourceClientAetna(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeBluebutton:
		return source.GetSourceClientBluebutton(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeCigna:
		return source.GetSourceClientCigna(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	// sandbox
	case pkg.SourceTypeAthena:
		return sandbox.GetSourceClientAthena(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeHealthit:
		return sandbox.GetSourceClientHealthit(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	case pkg.SourceTypeLogica:
		return sandbox.GetSourceClientLogica(env, sourceType, ctx, globalLogger, sourceCreds, testHttpClient...)
	default:
		return nil, nil, fmt.Errorf("could not find source type")
	}
}
