name: Source Development Tracker
description: This form is used to track the development progress for new EHRs/sources to be added to Fasten
title: "[Source]: "
labels: ["provider"]
projects: ["fastenhealth/fasten-sources"]
assignees:
  - AnalogJ
body:
  - type: input
    id: provider-name
    attributes:
      label: EHR/Platform Name
      description: What is the name of this Platform?
      placeholder: ex. Epic/Cerner/Allscripts
    validations:
      required: true
  - type: input
    id: chpl-website
    attributes:
      label: CHPL Website
      description: Please share a link to the [CHPL entry](https://chpl.healthit.gov/) for this EHR.
      placeholder: ex. https://chpl.healthit.gov/
    validations:
      required: true
  - type: input
    id: dev-website
    attributes:
      label: Developer Documentation
      description: Please share a link to the Developer Documentation for this EHR
      placeholder: ex. https://www.humana.com/api/fhir_docs
    validations:
      required: true
  - type: input
    id: endpoint-list
    attributes:
      label: Endpoint List
      description: Please share a link to the FHIR Endpoint List for this EHR
      placeholder: ex. https://mm-fhir-endpoint-display.prod.fhir.ema-api.com/
    validations:
      required: false
  - type: input
    id: provider-portal
    attributes:
      label: Example Patient Portal Login Website
      description: |
        Please share a link to and example provider's login page, where patients can access their health records.
        Use the following sites for searching for example patient portals:
        - https://explore.redoxengine.com/
        - https://enlyft.com/tech/products/practice-fusion
        - https://discovery.hgdata.com/product/practice-fusion
        - https://6sense.com/tech/electronic-health-records-ehr/practice-fusion-market-share
      placeholder: ex. https://ucsfmychart.ucsfmedicalcenter.org/ucsfmychart/Authentication/Login?
    validations:
      required: false
  - type: textarea
    id: developer-portal
    attributes:
      label: Developer Portal
      description: Please enter or share a link to the developer portal (where you can register app client id & secret)
      placeholder: ex. https://www.humana.com/
    validations:
      required: false      
  - type: textarea
    id: sandbox-credentials
    attributes:
      label: Sandbox Patient Credentials
      description: Please enter or share a link to sandbox credentials for this EHR
      placeholder: ex. https://www.humana.com/
    validations:
      required: false
  - type: textarea
    id: fasten-sources-definition
    attributes:
      label: Fasten Sources Definition
      description: Please enter a working Fasten Sources definition for this EHR
    validations:
      required: false
  - type: checkboxes
    id: status
    attributes:
      label: Platform Developer Readiness Checklist
      description: This checklist is used to track the status of an EHR platform, and how ready/compliant it's Patient Access APIs are
      options:
        - label: developer documentation
        - label: sandbox - endpoint published
        - label: sandbox - client registration
        - label: sandbox - test patient username & password
        - label: sandbox - no fees
        - label: sandbox - [inferno testing](https://inferno.healthit.gov/suites/g10_certification) passed
        - label: production - client registration
        - label: production - endpoint list published
        - label: production - endpoint catalog/health system info published
        - label: production - no fees
        - label: production - automatic client distribution
        
        
