name: CI
# This workflow is triggered on pushes & pull requests
on:
  pull_request:
    branches:
      - main
  push:
    branches: [ main ]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container: ghcr.io/packagrio/packagr:latest-golang
    env:
      STATIC: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: |
          go install github.com/golang/mock/mockgen@v1.6.0
          go generate ./...
          go test -coverprofile=coverage.txt -covermode=atomic -v ./...
      - name: Archive coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: ${{ github.workspace }}/coverage.txt
          retention-days: 1
      - name: Upload coverage report
        uses: codecov/codecov-action@v2
        with:
          files: ${{ github.workspace }}/coverage.txt
          flags: unittests
          fail_ci_if_error: true
          verbose: true
