name: Release
# This workflow is triggered manually
on:
  workflow_dispatch:
    inputs:
      version_bump_type:
        description: 'Version Bump Type (major, minor, patch)'
        required: true
        default: 'patch'
      version_metadata_path:
        description: 'Path to file containing Version string'
        required: true
        default: 'pkg/version/version.go'

jobs:
  release:
    name: Create Release Commit
    runs-on: ubuntu-latest
    # Service containers to run with `build` (Required for end-to-end testing)
    outputs:
      release_version: ${{ steps.bump_version.outputs.release_version }} # Map step output
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.25.7' # The Go version to download (if necessary) and use.
      - uses: actions/setup-node@v4
        with:
          node-version: 21
          registry-url: 'https://registry.npmjs.org'
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Bump version
        id: bump_version
        uses: packagrio/action-bumpr-go@master
        with:
          version_bump_type: ${{ github.event.inputs.version_bump_type }}
          version_metadata_path: ${{ github.event.inputs.version_metadata_path }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
#      - name: Generate JS Package
#        run: |
#          make build-js
#          cd js && npm version ${{ steps.bump_version.outputs.release_version }} --no-git-tag-version
      - name: Commit Changes Locally
        id: commit
        uses: packagrio/action-releasr-go@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
        with:
          version_metadata_path: ${{ github.event.inputs.version_metadata_path }}
      - name: Publish Release
        id: publish
        uses: packagrio/action-publishr-go@master
        env:
          # This is necessary in order to push a commit to the repo
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged

  deploy-s3:
    needs: release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      AWS_REGION: us-east-1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload CDN assets to S3
        run: |
          aws s3 cp catalog/brands.json "s3://${{ secrets.DEPLOY_BUCKET }}/catalog/${{needs.release.outputs.release_version}}/brands.json"
          aws s3 cp catalog/portals.json "s3://${{ secrets.DEPLOY_BUCKET }}/catalog/${{needs.release.outputs.release_version}}/portals.json"
          aws s3 cp catalog/endpoints.json "s3://${{ secrets.DEPLOY_BUCKET }}/catalog/${{needs.release.outputs.release_version}}/endpoints.json"

